### ISSUE TITLE
SNMP plugins

### ISSUE THREAD

**Issue by pfried** [jjethwa/icinga2#100]
I wanted to use the `snmp interface` service check, but got a file missing error, i then installed them via 

`sudo apt-get install nagios-snmp-plugins`

and the issue resolved. I am not firm with the whole check plugin structure, but i feel that it would be good because the director offers the plugin in its list and you get an error when you use it.

Keep up the good work!

**Comment by bebehei** [comment]
Nice catch. I'll fix it.

**Comment by bebehei** [comment]
It's fixed on latest master. Thank you for the detailed issue.

The new image is already on dockerhub, too. Just pulling the images, makes the fix.
