### ISSUE TITLE
locales not supported

### ISSUE THREAD

**Issue by bebehei** [jjethwa/icinga2#101]
icingaweb2 throws errors in the logfile (`/var/log/icingaweb2/icingaweb2.log`), cause my browser's locale is currently set to `de_DE` and in the container that locale is not generated:

```
2017-05-22T21:33:39+02:00 - ERROR - Icinga\Exception\IcingaException in /usr/share/php/Icinga/Util/Translator.php:181 with message: Cannot set locale 'de_DE' for category 'LC_ALL'
```

Literally, my logfile contains just garbage. The relation of garbage and useful loglines is way out of balance:
```
$ grep -v de_DE icingaweb2.log | wc -l
382
$ wc -l icingaweb2.log
119739 icingaweb2.log
```

The container should support translation without any exceptions.

**Comment by jjethwa** [comment]
@bebehei 

Looks like we need to install the locales package and also follow the steps outlined here:

https://github.com/Icinga/icingaweb2/issues/1986

**Comment by edy** [comment]
Their steps didn't work for me, so i use this in my icinga2 image (and some other unrelated images):
```
# generate locale
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
	echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen && \
	locale-gen de_DE.UTF-8 && \
	dpkg-reconfigure -f noninteractive locales && \
	/usr/sbin/update-locale LANG=de_DE.UTF-8 && \
	locale
```

A `locale -a` gives me:
```
C
C.UTF-8
POSIX
de_DE.utf8
en_US.utf8
```

After restarting the container, the error is gone.

**Comment by jjethwa** [comment]
Thanks for the tip @edy 😄

**Comment by bebehei** [comment]
Well, the locale used in icingaweb2 is determined by the browser's locale.

For myself, I have not seen the issue yet. I'm using en_US locale. But it's just spamming my logfile, as my colleagues are using german as their default.

The actual problem is, that the locale is not generated and therefore icingaweb2 can't load it.

I don't know what the correct solution is, cause I don't consider generating all possible locales as a solution.
