### ISSUE TITLE
debian:stretch php sessions folder has moved

### ISSUE THREAD

**Issue by cpjolly** [jjethwa/icinga2#107]
With the change to debian:stretch, php also has changed to php7.0, which uses the following location for php session storage

/var/lib/php/sessions

rather than

/var/lib/php5/sessions

There may be other places, but minimum the following 3 files should be updated:
README.md
docker-compose.yml
content/opt/setup/icingaweb2

**Comment by jjethwa** [comment]
Hi @cpjolly 

Thanks for reporting the issue.  We'll work on it and get back to you once merged 😄

**Comment by bebehei** [comment]
Thanks @cpjolly, this is "fixed" in master. A notification about having the wrong php sessions folder mounted will get merged with #110.
