### ISSUE TITLE
External MySQL/Maria DB

### ISSUE THREAD

**Issue by aleliga** [jjethwa/icinga2#109]
Hi,
It's possible to externalize DB?
Use an external DB could be usefull

**Comment by bebehei** [comment]
Well, I thought about this previously, too. Especially in terms of reducing the image size. The mysql-stuff inside the debian image is quite big, but the standard mysql containers are this, too.

In general, it's possible to use an external DB, but I don't know yet, what you have to change. Currently everything is hardcoded to `localhost`. Parametrizing it with an ENV-Variable, which defaults to `localhost` may be an option. But I'm really not sure if it's worth the effort.

**Comment by bebehei** [comment]
Well, I have to say, this might be a good feature, as a container restart is mainly slowed down by MySQL.

**Comment by tranthanhbao2207** [comment]
+1, i have a center mysql container . I want to link icinga2 to that DB

**Comment by bebehei** [comment]
@aleliga @tranthanhbao2207 I've added support to specify an external MySQL DB in #112 and it's working™️. But before merging it into master, I'd like to have some more testing. Might you want to volunteer and test it?
