### ISSUE TITLE
MySQL DBs get doubly instructed

### ISSUE THREAD

**Issue by bebehei** [jjethwa/icinga2#111]
Hey @jjethwa, I'm working on #109 currently.

But I'm wondering:

There gets an [`icinga2idomysql` DB](https://github.com/jjethwa/icinga2/blob/04976110b3f721e3d1b587c6fb4db6c31add7708/content/opt/setup/icinga2#L61) seeded, and also there gets an [`icinga` DB](https://github.com/jjethwa/icinga2/blob/04976110b3f721e3d1b587c6fb4db6c31add7708/content/opt/setup/icinga2#L37) seeded. But it seems, that the `icinga`-DB is actually never used.

Tracking it down with blame, it's there since ever: c967b196bf543127ff6c3e4bb8ab1b15a764ed20

Is there a reason for it? Actually, there should only be 3 DBs (director, ido and web). I'm bluffed, that I've never seen that.

**Comment by bebehei** [comment]
Additionally, both files are exactly the same, as md5sum shows:

```
db2b00613b71f9098dec66978d687a45  /usr/share/dbconfig-common/data/icinga2-ido-mysql/install/mysql
db2b00613b71f9098dec66978d687a45  /usr/share/icinga2-ido-mysql/schema/mysql.sql
```

**Comment by jjethwa** [comment]
Hi @bebehei 

Whoops!  Most likely a change from a pre-release version that I missed 😛
