### ISSUE TITLE
Feature Request: Filtering on Notification Type in Notification History (icinga-web2)

### ISSUE THREAD

**Issue by robertkrenn** [jjethwa/icinga2#115]
In greater environments in the historical view of notifications there are quite fast a lot of entries for all sent notifications. Because mail notifications are not as high in priority than sms notifications (the "r" in smtp stands for "realtime" ;-) ), it would be really useful to be able to filter on the notification type of the sent notifications, to have a quick summary what alerts where triggered on sms in the last x days.

**Comment by bebehei** [comment]
Well, I don't fully understand your problem, but it seems to be an upstream issue. You probably want to open up an issue at [the main icingaweb2 repository](https://github.com/Icinga/icingaweb2). This here is just a docker container, packaging icinga2.

If the bug really holds up for this repository, please reopen the issue again and elaborate it a bit more.
