### ISSUE TITLE
Password security

### ISSUE THREAD

**Issue by falnos24865** [jjethwa/icinga2#117]
All passwords (both database and webadmin) are shown through standard out. This means anyone with access to view the logs can gain admin access to the dashboard.

I understand doing this if it is a default setup as that can be considered not secure anyway. But if I am specifying a web admin password using an environment variable it should not be displayed in the logs.

**Comment by bebehei** [comment]
That's a valid point. Thank you for reporting this issue.

But TBH, this is a quite low hanging fruit everything you mention, is set inside [`/opt/run`](https://github.com/jjethwa/icinga2/blob/master/content/opt/run). Would you mind submitting a PR? I'm currently short on time.
