### ISSUE TITLE
Feature request: Support adding custom scripts using volumes

### ISSUE THREAD

**Issue by sschulze** [jjethwa/icinga2#119]
Currently it is not possible to add a (persistent) custom check-script without extending the image.
So it'd be great if one could simply add these custom scripts to a volume.

I'm rather new to Icinga, but if you could give me some guidance I would try to contribute a pull request.

**Comment by jjethwa** [comment]
Hi @sschulze 

You could do this by using one of the built in volumes or adding your own volume at container runtime.  Is this an acceptable solution?

**Comment by bebehei** [comment]
Actually, this had been trivial to me to include scripts by myself and I never thought somebody would struggle here. But as this is the case, I think we should mention it somewhere (or in general write a small introduction tutorial also covering this).

**Comment by sschulze** [comment]
It's really trivial after learning, that I have to absolute paths in commands.conf... :smile:

**Comment by jjethwa** [comment]
Glad you got it working @sschulze  😄

**Comment by aleliga** [comment]
I've tried the custom script, it's executed at any container restart, in my case make container unusable after restart
I'have added a creation of a file at end of script:
touch /root/finish1strun
and done a test of the existance at the start of script
test -x /root/finish1strun && exit 0
This should prevent the run at restart

**Comment by jjethwa** [comment]
Hi @aleliga 

Can you open a new issue and provide some more details like any errors from the docker run or container log?
