### ISSUE TITLE
module graphite 0.9.0 on jjethwa/icinga2 have problem

### ISSUE THREAD

**Issue by cyrus0880** [jjethwa/icinga2#121]
how to fix this problem
on icingaweb > graphite > hosts
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8', query was: SELECT ho.name1 AS host_name, h.display_name COLLATE latin1_general_ci AS host_display_name, hs.check_command AS host_check_command, hcv_check_command.varvalue AS _host_check_command FROM icinga_objects AS ho
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_check_command ON h.host_object_id = hcv_check_command.object_id AND hcv_check_command.varname = 'check_command' COLLATE latin1_general_ci ORDER BY h.display_name COLLATE latin1_general_ci ASC LIMIT 25

 on icingaweb > graphite > hosts services
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8', query was: SELECT so.name1 AS host_name, h.display_name COLLATE latin1_general_ci AS host_display_name, so.name2 AS service_description, s.display_name COLLATE latin1_general_ci AS service_display_name, ss.check_command AS service_check_command, scv_check_command.varvalue AS _service_check_command FROM icinga_objects AS so
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id
LEFT JOIN icinga_customvariablestatus AS scv_check_command ON s.service_object_id = scv_check_command.object_id AND scv_check_command.varname = 'check_command' COLLATE latin1_general_ci ORDER BY s.display_name COLLATE latin1_general_ci ASC LIMIT 25

**Comment by jjethwa** [comment]
Hi @cyrus0880 

Please refer to: https://github.com/Icinga/icingaweb2/pull/3170

We'll need to wait for it to be fixed 😞

**Comment by bebehei** [comment]
@jjethwa The issue you referenced is already fixed. What should be done here now?

**Comment by jjethwa** [comment]
Hmm, I don't see a new PR from the user that created the issue.  So he might still be working in it.  In any case, I think we can go ahead and close this issue as it's not a container specific problem 😄
