### ISSUE TITLE
Inline comments future deprecation

### ISSUE THREAD

**Issue by bebehei** [jjethwa/icinga2#122]
Docker's inline comments are marked as deprecated a while ago. This image has to find a replacement for this, too. I had been quite angry about this, because it's one of the best things in `Dockerfile` to insert structure without splitting into multiple `RUN`s.

I finally found somewhere else a proper replacement:

```
 && command \
# comment
&& command \
&& command
```

```
 && command \
`# comment` \
&& command \
&& command
```

Just "executing" the comment is shitty, but so genius.

TODO with one of the next PRs.

**Comment by jjethwa** [comment]
Thanks for the heads up, @bebehei 

Didn't know they deprecated inline comments...makes no sense to me! 😲

**Comment by bebehei** [comment]
The warnings have vanished in meantime. It looks like some others have already fixed this in a PR in the docker repo.
