### ISSUE TITLE
Unable to change timezone in jordan/icinga2 docker image

### ISSUE THREAD

**Issue by ajayan769** [jjethwa/icinga2#123]
Hi All,

I am trying to test a monitoring tool using icinga2 for that I have used the docker image "jordan/icinga2" (https://hub.docker.com/r/jordan/icinga2/). The installation was good and am able to monitor my servers/hosts. But the issue I'm facing is timezone, the icinga2 showing the UTC timezone where I want to use IST (Asia/Kolkata)......

Changed the timezone from php.ini (/etc/php/7.0/cli/php.ini) but no luck
Can anyone please let me know the possible workaround in this issue?
Thanks in advance

**Comment by bebehei** [comment]
Just set the TZ environment variable to your proper location.

**Comment by bebehei** [comment]
@ajayan769 has reacted with "thumbs up". I guess this issue is solved.

**Comment by jjethwa** [comment]
Yep, should be as easy as starting the container with
```
-e TZ=Asia/Kolkata
```

**Comment by ajayan769** [comment]
Yes, the issue has been resolved

**Comment by magnusbaeck** [comment]
Setting the TZ variable doesn't make any difference for me; The icinga.long_date_time macro remains UTC, just like all log file timestamps. The only place where it works is when I start a shell inside a running container with `docker exec -it $CONTAINER bash`. Given that start-stop-daemon(8) which is used to start e.g. Icinga starts its child processes with a clean environment this behavior is unsurprising. Am I missing something?

What I'd expect _would_ work is running something like

```sh
echo $TZ > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata
```

in an /opt/setup script.

**Comment by jjethwa** [comment]
Hi @magnusbaeck 

Can you confirm that the TZ you are setting is also the same one set in the php.ini?

**Comment by magnusbaeck** [comment]
> Can you confirm that the TZ you are setting is also the same one set in the php.ini?

I haven't touched php.ini (so it seems the date.timezone setting is unset). My concern is the timezone used by Icinga and Apache, not Icinga Web, so I'd expect the contents of php.ini to be immaterial.

**Comment by jjethwa** [comment]
Hi @magnusbaeck 

Ah, sorry, I had misunderstood. As far as I know, setting the TZ variable should be enough.  You might need to check with the core project: https://github.com/Icinga/icinga2/issues

**Comment by magnusbaeck** [comment]
I don't think this is a core issue. Any TZ value set when starting the Docker container won't reach Icinga since the TZ variable isn't propagated when Icinga is started by start-stop-daemon(8). You can verify this by inspecting /proc/$PID_OF_ICINGA/environ. Absent that variable Icinga will read /etc/localtime, which in this Docker image is a symlink to /usr/share/zoneinfo/Etc/UTC. Anyway, I'll try the solution I suggest above and see if it even works. If so I'll send a PR.

**Comment by jjethwa** [comment]
Thanks, @magnusbaeck 👍
