### ISSUE TITLE
Setting name and password in docker-compose.yml has no effect

### ISSUE THREAD

**Issue by PJaros** [jjethwa/icinga2#125]
I've changed name and password in my docker-compose.yml an recreated both containers. But I can't login with the set values but can still login with icingaadmin/icinga.

**Comment by bebehei** [comment]
Sorry, I cannot reproduce this.

- Do you run the latest image from dockerhub?
- Are your variable names named correct?

**Comment by bebehei** [comment]
ping @PJaros. Is this still an issue for this? Have you resolved it?

**Comment by PJaros** [comment]
Sorry, my mistake: 
I was declaring "environment: 
 - ..." twice in my docker-compose.yml thus rendering the first part useless. :P
