### ISSUE TITLE
error - Method eventuallyAddNameRestriction does not exist under icinga directo->service->apply service rule

### ISSUE THREAD

**Issue by subinmath** [jjethwa/icinga2#127]
I am gettin an Method eventuallyAddNameRestriction does not exist

under icinga director->service->apply service rule
Attaching below screenshot

**Comment by subinmath** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/17119174/34670129-030567e4-f49b-11e7-8277-83c34539c503.png">

**Comment by subinmath** [comment]
<img width="1199" alt="screen shot 2018-01-08 at 5 36 10 pm" src="https://user-images.githubusercontent.com/17119174/34670147-157e3a90-f49b-11e7-8774-c564fd631776.png">

**Comment by bebehei** [comment]
I don't know what he did, but this problem occured already another time. He said "updating to git master fixed it". See #124

**Comment by subinmath** [comment]
any work arounds?

**Comment by subinmath** [comment]
I am seing errors in other places as well IcingaDirector->Notifications->Apply
<img width="977" alt="screen shot 2018-01-09 at 4 52 35 pm" src="https://user-images.githubusercontent.com/17119174/34718701-b250d81a-f55d-11e7-9520-a22d31e6a0d1.png">

**Comment by jjethwa** [comment]
HI @subinmath 

Can you try updating Director to the latest git master as well?  We may need to do the same for the image, but need to confirm.  Thanks 😄

**Comment by subinmath** [comment]
@jjethwa whats the step to update director, i tried replacing the director directory with new files but it didnt work.. can you please let me know the steps

**Comment by bebehei** [comment]
@jjethwa Might you want to trigger a rebuild of this image on dockerhub? A rebuild for the `latest` tag on dockerhub should resolve this and does not break anything.

**Comment by jjethwa** [comment]
@bebehei & @subinmath  Triggered a build of the latest tag 😄

**Comment by chazwize** [comment]
me too

**Comment by bebehei** [comment]
> me too

Thank you @chazwize  for these wise words. We value your contributions high! ... but please contribute! The information if the **current** image fixes it, would have highest value here in this issue 😆

**Comment by subinmath** [comment]
@jjethwa @bebehei I pulled the latest image but still same error

**Comment by bebehei** [comment]
Well, when I rebuilt it locally, the Problem has vanished. Does your container still boot with the old image?

**Comment by subinmath** [comment]
nope i deleted the old one let me check again

**Comment by subinmath** [comment]
i am using the compose file from the repo 
"version: '2'
services:
  icinga2:
    image: jordan/icinga2:latest
    ports:
     - "8080:80"
    restart: on-failure:5
    hostname: icinga2"

**Comment by bebehei** [comment]
> @bebehei i am using the compose file from the repo

That doesn't say anything. `docker images` might help more.

**Comment by bebehei** [comment]
And do noy forget to run `docker-compose down`. Only this will remove the old container and will tell `docker-compose up` to use the new image.

**Comment by subinmath** [comment]
Yup i tried deleting old images and getting the new one up. but error is same

**Comment by jjethwa** [comment]
@subinmath Can you provide the steps to reproduce the issue?  I'm unable to reproduce as of yet 😢  Need to determine if this is caused by one of your configs, something in the container, or an app issue itself.

**Comment by bebehei** [comment]
ping @subinmath

**Comment by bebehei** [comment]
More than two weeks have gone by. I guess, the problem got solved.
