### ISSUE TITLE
NRPE ! connection reset by peer . 

### ISSUE THREAD

**Issue by PrashanthPatil1987** [jjethwa/icinga2#131]
```
/usr/lib/nagios/plugins/check_nrpe -2 -H XXXXXXX -c check_load
CHECK_NRPE: Error - Could not connect to 96.118.209.213: Connection reset by peer

/usr/lib/nagios/plugins/check_nrpe -2 -H XXXXXXXX -n -c check_load
OK - load average: 0.00, 0.03, 0.05|load1=0.000;64.000;80.000;0; load5=0.030;40.000;64.000;0; load15=0.050;16.000;24.000;0;
```

It's working with no_ssl option which is fine , changed nrpe_check.cfg to allow no_ssl, but that config changes seems to have no effect.  

```
define command {
    command_name    check_nrpe
    command_line    /usr/lib/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -n -c $ARG1$
}
```

It seems this issue is addressed in here https://github.com/NagiosEnterprises/nrpe/issues/113 and dockerfile needs to be updated to Debian 9.1 stable .

**Comment by jjethwa** [comment]
Hi @PrashanthPatil1987 

We use debian:stretch as the base image with is currently set to 9.3.  You can confirm this by executing this command in your container:

```
$ cat /etc/debian_version
9.3
```

**Comment by bebehei** [comment]
> ```
> define command {
>     command_name    check_nrpe
>     command_line    /usr/lib/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -n -c $ARG1$
> }
> ```

This isn't even proper icinga2 markup. This is the old icinga/icinga1/nagios markup. @PrashanthPatil1987 You probably hit the wrong bugtracker with your issue.
