### ISSUE TITLE
Unable to add new host error Trying to recreate icinga_host (hostname) (DbObject.php:780)

### ISSUE THREAD

**Issue by chaosjester** [jjethwa/icinga2#134]
Hi,
I have just pulled the latest container and after adding a host template and group, I go to create a new host and get the error:

Trying to recreate icinga_host (hostname) (DbObject.php:780)

There is nothing about the error in the icingaweb2.log or icinga2.log so I am not too sure what else to look at, has this happened for anyone else and have they managed to get around it?

TIA

**Comment by bebehei** [comment]
No problems at all for me.

What does `docker images --filter=reference=jordan/icinga2` give?

**Comment by chaosjester** [comment]
`docker images --filter=reference=jordan/icinga2` gives: 
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jordan/icinga2      latest              5596ae908f64        2 days ago          707MB
```

**Comment by bebehei** [comment]
- All fine there. Could you please give some more detailed steps?
- Have you had icinga2 installed previously?
- If so, have you installed the director schema updates?

**Comment by chaosjester** [comment]
I had pulled the image and made several containers with the the image so I stopped everything and did `docker system prune` to remove everything. I then ran `docker run -p 80:80 -t jordan/icinga2:latest` which pulled the image and started the container. 
I opened icingaweb2 and logged in, went to the director page and deployed the waiting changes. Then in the director host section I created a hostgroup which was successful, then a host template which was also successful. Then when adding the host, I select the host template and fill in the rest of the mandatory fields and click add, this is when the error appears.
Screenshot attached
![image](https://user-images.githubusercontent.com/15764080/35710616-95971d08-080c-11e8-937d-1eba27bf8343.png)

**Comment by bebehei** [comment]
Is this a fresh DB? Have you initialized it today or have you initialized it a few weeks/months ago and pullled now the new image but still on the old Database?

**Comment by chaosjester** [comment]
It's fresh as of 2 days ago, the container was newly created.

**Comment by chaosjester** [comment]
So just for "fun" I dexided to do a full standard incinga2/icingaweb2 install on my server and ran in to the same issue, so its either something I am doing wrong or an issue with icinga itself, nothing to do with this docker image. 

Can close this off and I will post on the icinga forums.

Thanks for looking in to this though, once I figure out what I am doing wrong I will go back to the container ;)

**Comment by bebehei** [comment]
> EDIT: Yeah it was me, sorry about that... was not understanding the configuration items it was actually asking for

So, you've solved this problem!?

**Comment by bebehei** [comment]
> So, you've solved this problem!?

ping @chaosjester

**Comment by bebehei** [comment]
I guess it's solved.

**Comment by cowboy6** [comment]
Hi, I'm having this issue too. [https://imgur.com/ewTpTPN](url)

**Comment by cowboy6** [comment]
Hi, I'm having this issue too. https://imgur.com/ewTpTPN

**Comment by jjethwa** [comment]
HI @cowboy6 

Can you provide the log output from when you get the error?  That'll help us determine if it's a container or app issue.

**Comment by cowboy6** [comment]
@jjethwa Where can I find log output? Under /var/log/apache2, /var/log/icinga2/, /var/log/icingaweb2 and docker logs I cannot find any useful information.

**Comment by bebehei** [comment]
@cowboy6 These are exactly the right points to search for the logfiles. There are no other logs. Also, I think there won't get anything logged.

@chaosjester Could you please provide your solution!?

**Comment by chaosjester** [comment]
Sorry for my late reply, I think the issue was caused by having either the host template, hostname and host address as the same “server.domain.com”, I have not had a chance to revisit this but it was having 2 of those fields with the same value that seemed to cause the issue.

Sent from Mail for Windows 10
