### ISSUE TITLE
Issue on graphite url 

### ISSUE THREAD

**Issue by Revolucio** [jjethwa/icinga2#136]
Hi,

I found an issue with the graphite url. 

I see the error : 

`Missing "graphite.url" in "/etc/icingaweb2/modules/graphite/config.ini"`

To fix it I change on /etc/icingaweb2/modules/graphite/config.ini the parameter _web_url_ for _url_

Bests

**Comment by bebehei** [comment]
[Well, the author of this commit did something not so smart. Just renamed every parameter without any fallback](https://github.com/Icinga/icingaweb2-module-graphite/commit/2d5f858da50d2d5c277ee7cfa9c33f338a2443a2).

Thanks @Revolucio for reporting this.
