### ISSUE TITLE
Monitor printers

### ISSUE THREAD

**Issue by ajayan769** [jjethwa/icinga2#138]
Hi,

I want to monitor network printers (Canon) using icinga as mentioned here (https://www.icinga.com/docs/icinga1/latest/en/monitoring-printers.html), but I am unable to do this. Can anyone please help me to configure printer monitioring on my icinga docker image?

Thank you.

**Comment by bebehei** [comment]
It's basically all about: Find a working plugin. Write the checkcommand definition. Then define a host for your canon printer. Define a service in this host or (or create a matching apply rule), which uses your checkplugin. And that's it.

To do this, mount your `/etc/icinga2` folders and mount your check plugin directly into `/usr/lib/nagios/plugins` (e.g.: `-v $PWD/check_canon:/usr/lib/nagios/plugins/check_canon`).

And then write your configuration in the icinga2volume and there in `conf.d`. You then have to go on and read the docs about [how configure icinga2 in detail](https://www.icinga.com/docs/icinga2/latest/).

- The link you reference is icinga (== icinga 1.x). This image provides icinga2. The mentioned printer is a HP one. So the configuration can't work in at least two points.

**Comment by ajayan769** [comment]
@bebehei Thank you for your inputs. Will check the mentioned solution.

**Comment by ajayan769** [comment]
@bebehei I was wondering whether it's possible to map tactical overview information in Icinga to other dashboards.

Our aim is to see the Hosts and service status at one place instead of going Icinga>>Tactical overview.
Please suggest.

**Comment by bebehei** [comment]
@ajayan769 I'm not an icinga2 superguru and I'm not using every feature of icinga2 and I'm not willing to give 1:1 support which is not directly related to this image. If you have pure icinga2 questions, please ask them on the [mailinglist](https://lists.icinga.org/mailman/listinfo) or in the icinga forums.

**Comment by jjethwa** [comment]
Forum link: https://monitoring-portal.org/woltlab/index.php?board/117-icinga-2/

**Comment by ajayan769** [comment]
@bebehei Sorry, and will follow the Icinga forum. 
@jjethwa thanks
