### ISSUE TITLE
New in docker, i miss something

### ISSUE THREAD

**Issue by AlucardleVash** [jjethwa/icinga2#14]
Hello,

I want to use your image, it's seem's perfect for me.

i run the following command :

    docker run -h icinga -e IDO_PASSWORD="icinga" -v /opt/icinga/var_lib_mysql:/var/lib/mysql -p 5665:5665 -p 80:80 --name icinga -t jordan/icinga2:latest

    =>Initializing databases and icinga2 configurations.
    =>This may take a few minutes
    [FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!

It's not possible to just mount my folder ?

**Comment by jjethwa** [comment]
Hi @AlucardleVash 

Does that volume contain database files already?   If not, I find it easier to start a container then export the files into the volume.

**Comment by AlucardleVash** [comment]
Hi, thank's for you reply.

Yes, i try to create a container without -v option, copy the content of volume in one of my host directory and after, destroy the container and rerun with -v option, and i have the same IDO_PASSWORD environnement.

I not more at work today and tomorrow i'm busy, but i think work on it sunday or monday. i try to post  here more details of my trouble, thank's for you help.

Also, if you have any ressources on icinga2 probe side, it's could be great :D

**Comment by jjethwa** [comment]
Hi @AlucardleVash 

Sounds good!   I can definitely help more on Monday.   Do you want know more about the local agent checks or something else?   Thanks :)

**Comment by AlucardleVash** [comment]
Yes, that's not really my trouble, more my next stop, but i want to know more how local agent check to monitor your server ? Does you use nagios probe or icinga bin ? maybe by email : pbrun.proatgmaild0tcom

**Comment by AlucardleVash** [comment]
Ok now everything seem's work fine.
I think it's simple a mistake during setup, i miss copy on directory or something like that.

**Comment by jjethwa** [comment]
Hi @AlucardleVash 

That's great news!   I'll go ahead and close this issue.   Please let me know if you need help in the future :)
