### ISSUE TITLE
Can't run with external database

### ISSUE THREAD

**Issue by morsik** [jjethwa/icinga2#145]
Hi, I'm trying to start `jordan/icinga2` with external database since the beggining so I use:

```
# docker run -it \
  --mount "type=bind,source=/srv/icingaweb2-sessions,target=/var/lib/php/sessions" \
  -e 'DEFAULT_MYSQL_HOST=mysql' \
  -e 'DEFAULT_MYSQL_USER=icinga' \
  -e 'DEFAULT_MYSQL_PASS=pass' \
  -e 'ICINGA2_IDO_MYSQL_DATA=icinga_ido' \
  -e 'ICINGAWEB2_MYSQL_DATA=icinga_icingaweb2' \
  -e 'ICINGAWEB2_DIRECTOR_MYSQL_DATA=icinga_director' \
  jordan/icinga2
```

But it fails with no any interesting error:
```
Generating locales (this might take a while)...
Generation complete.

Site 000-default already enabled
Site icingaweb2-ssl already disabled
Site icingaweb2-ssl-redirect already disabled
/opt/helpers: line 60: MYSQL_ROOT_PASSWORD: unbound variable
run-parts: /opt/setup/50-icinga2 exited with return code 1
```

I looked into `/opt/setup/50-icinga2` which tried to import database so I imported it manually, but actually - I have no idea what's wrong here, and error is meaningless.

**Comment by bebehei** [comment]
> /opt/helpers: line 60: MYSQL_ROOT_PASSWORD: unbound variable

Quickfix: add `-e MYSQL_ROOT_PASSWORD=""` to your docker run call.

---

Other question: Have you intiialized the DBs manually? If not, please give the root password via `-e MYSQL_ROOT_PASSWORD="<your password>"`. Then the container will care about mysql schemas.

**Comment by morsik** [comment]
I don't want to provide root password for this cause I'm using my shared database - not instance dedicated for Icinga. There should be some other way to import database that doesn't needs mysql root account.

I tried to import IDO2 DB, but error is meaningless and doesn't tell where it crash and what's wrong exactly.

**Comment by bebehei** [comment]
If you've still got (different) problems, please report back.
