### ISSUE TITLE
Unable to log in on fresh container

### ISSUE THREAD

**Issue by zlesnr** [jjethwa/icinga2#146]
When starting a new container, I get the following message in the start up.

```
Module path "/etc/icingaweb2/userModules" does not exist
Module path "/etc/icingaweb2/userModules" does not exist
Module path "/etc/icingaweb2/userModules" does not exist
```

I believe this has something to do with the error that I get when I try to log into icingaweb.

```

#0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2280): Icinga\Web\Form\Element\CsrfCounterMeasure->isValid('2086098592|213a...', Array)
#1 /usr/share/php/Icinga/Web/Form.php(1282): Zend_Form->isValid(Array)
#2 /usr/share/php/Icinga/Web/Form.php(1156): Icinga\Web\Form->isValid(Array)
#3 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(50): Icinga\Web\Form->handleRequest()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('loginAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

I've also tried the 2.8.0 image, but also see this on the latest image that was pushed a day ago.  What am I missing?

**Comment by jjethwa** [comment]
Hi @zlesnr 

Sorry, I was away from my laptop for a few weeks.  I'm using the default credentials icingaadmin:icinga with a fresh container and  can login to the icingaweb2 interface without issues. This is using the latest image from Docker Hub.  Can you confirm the behaviour you are seeing?

**Comment by zlesnr** [comment]
```

**Comment by bebehei** [comment]
@zlesnr Sorry, but a simple  `docker run --rm -t -i -p 8080:80 jordan/icinga2` won't yield any problems to me. I can easily login and have no problems.

Could you please show your config and/or `docker run` command?

**Comment by jjethwa** [comment]
Hi @zlesnr 

Not sure if this will make a difference, but try running the container without --rm and -i for now.  All the relevant logs should be under /var/log/ apache2 and /var/log/icingaweb2

**Comment by zlesnr** [comment]
On point to note, I'm running `18.03.1-ce-mac65` and failing to log in.  My teammate is running `17.12.0-ce-mac49` and he is able to log in.

**Comment by bebehei** [comment]
@zslesnr: You're sure that the images of both containers are the same version?

**Comment by jjethwa** [comment]
@zlesnr 

I have a feeling something in the (docker for mac) networking setup is causing the CSRF issue 😞

**Comment by zlesnr** [comment]
@bebehei Same version of the container.  I have another teammate on `18.03.1-ce-mac64` that can log in as well.  I'm less sure that it's a docker version issue.

@jjethwa Okay.  What settings on my machine might cause this issue?

**Comment by jjethwa** [comment]
@zlesnr 

I'm not sure as I don't own a Mac to test on, but I'd suggest going through the changelog for 18.03.1-ce-mac65 and see what changed from 18.03.1-ce-mac64.  Maybe a docker version change if that was included.  I use CoreOS as my docker host and don't have issues (so far) 😛

**Comment by bebehei** [comment]
browser != container. Use a fresh profile in **your browser**. And enable cookies and disable any adblocker.

Then spin up your old container or a fresh one. and test it again.

**Comment by zlesnr** [comment]
Yep, real weird.  Using an incognito window allows me to log in. Thanks for the debugging.  Still not sure what the issue is with my primary browser.
