### ISSUE TITLE
The Icingaweb2 master isn't compatible with the Dockerfile

### ISSUE THREAD

**Issue by gauria** [jjethwa/icinga2#148]
Hello,

We have verified that the Dockerfile does not build the docker correctly because of using the master branch in icingaweb2

**Comment by bebehei** [comment]
Sorry, but the current [image uploaded on dockerhub](https://hub.docker.com/r/jordan/icinga2/builds/bpb2qudwo3dzjclselxufz7/) works properly. If you've got trouble to build the Docker image from the gitrepository and the current `master` `HEAD` commit is wrong, please add a build argument to your docker build instruction with `docker build --arg GITREF_ICINGAWEB2=<commitid|tag|branch>` to select a proper tag.

If you're interested in a permantent fix, please look at #137 (and fix the issue there :wink:)
