### ISSUE TITLE
Can't login to icingaweb2

### ISSUE THREAD

**Issue by zxkane** [jjethwa/icinga2#15]
I followed the instructions in [page](https://registry.hub.docker.com/u/jordan/icinga2/). The icinga passwords are overridden via environment of docker.

Below is output in logs,
```
===================================================================
MySQL user 'root' has no password but only allows local connections
MySQL user 'debian-sys-maint' password set to 6KXKZdrJ4kcBUhQ
MySQL user 'icinga' password set to vmeoperation
MySQL user 'icinga2-ido-mysq' password set to 0y77YAgsXoWXqCd
MySQL user 'icinga-web' password set to vmeoperation
MySQL user 'icingaweb2' password set to vmeoperation
===================================================================
```

However I always failed to login icinga-web2, both using the password given as environment and the default one **icingaadmin:icinga** given in docker hub do not work.

Looks like the password of icingaweb still is not overridden by the one given in environment, using the default one **root:password** works.

Could you suggest what's wrong?

**Comment by jjethwa** [comment]
Hi @zxkane 

Those variables are for the database not the icingaweb or icingweb2 frontends.  For the frontend account, they default to root:password for icingaweb and icingaadmin:root for icingweb2.    I've tested the container and those defaults are working.   Could you have changed the frontend password before?   You might need to reset them.   Let me know :)

**Comment by zxkane** [comment]
Jordan, thanks for your hint.

I found something strange. If I don't specify any environment for password, the default one **icingaadmin:icinga** works fine to login icingaweb2. If you ran the container with my password environment, the default credential can not login *icingaweb2*. The credential of icinga-web is not impacted by environment variable.

I ran the container via below command line,
```shell
docker run --name my-icinga2 -p 8000:80 -d -e ICINGA_PASSWORD="vmeoperation" -e ICINGA_WEB_PASSWORD="vmeoperation" -e ICINGAWEB2_PASSWORD="vmeoperation" -t jordan/icinga2:latest
```

Looks like those password are the users of mysql, is there any way to specify the default credential for *icingaweb2* web interface when starting container?

Thanks.

**Comment by jjethwa** [comment]
Hi @zxkane 

There is no way currently to specify the passwords for the web interface.   I can look into setting that up though.   For our use, we use ldap authentication so we have that config in /etc/icingaweb2 and do not use the old icingaweb interface.  The nice part about that is not having to worry about credentials as you move to a new container.

**Comment by gvenka008c** [comment]
@jjethwa Can you throw some light on using ldap authentication steps with icinga?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Check out the LDAP section: https://github.com/Icinga/icingaweb2/blob/master/doc/05-Authentication.md
