### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by ajayan769** [jjethwa/icinga2#150]
Hi,

I am getting an uneven timestamp while generating reports from History>> Event grid 

![image](https://user-images.githubusercontent.com/34644256/40178069-0f628c38-59fe-11e8-83e7-7286b29c205f.png)

After downloading the report as CSV file from the dropdown it's showing like this. 

![image](https://user-images.githubusercontent.com/34644256/40178107-2a42f8da-59fe-11e8-8dd8-9acf8a5cd02f.png)

Can anyone please suggest me why it's showing in such format instead of correct format?
I am using IST timezone for the Icinga instance.

Thank you in advance.

**Comment by bebehei** [comment]
Have you set the `TZ` env variable?

**Comment by ajayan769** [comment]
Yes, it's set to IST timezone.

**Comment by jjethwa** [comment]
Hi @ajayan769 

Have you set the timezone for the account you are using to login to Icinga Web 2?

**Comment by ajayan769** [comment]
@jjethwa Yes, it's already set to IST (Asia/kolkata)

![image](https://user-images.githubusercontent.com/34644256/40220472-dc89a9d8-5a96-11e8-9227-99649efc77f1.png)

**Comment by jjethwa** [comment]
Hi @ajayan769 

I converted some of the timestamps provided and they seem to be within the acceptable range.  What are you expecting?

**Comment by ajayan769** [comment]
@jjethwa may I know how did you convert the time ranges? I expected something like 10.30, time format.

**Comment by jjethwa** [comment]
Hi @ajayan769 

Ah, sorry about the confusion!  Those timestamps are always stored in epoch/Unix time.  You can convert using the date command on Linux or date/calendar libraries.

**Comment by ajayan769** [comment]
Thank you very much @jjethwa it worked. You may please close this thread.
