### ISSUE TITLE
upgrade to newest latest image caused error in icingaweb2

### ISSUE THREAD

**Issue by christianuhlmann** [jjethwa/icinga2#155]
hi

i use this container for round about one year, thanks for your work.
today i try tu upgrade to the latest version from 2.5.1 to 2.5.3

after recreating the containers i get the following error in icingaweb2:

/var/log/icingaweb2/icingaweb2.log
> 2018-07-08T20:09:06+02:00 - ERROR - ErrorException in zend.view:///usr/share/icingaweb2/application/views/scripts/layout/menu.phtml:0 with message: Method Icinga\Web\Navigation\Renderer\RecursiveNavigationRenderer::__toString() must not throw an exception, caught Error: Call to undefined method Icinga\Data\Db\DbConnection::getConfig()
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

browser

> Method Icinga\Web\Navigation\Renderer\RecursiveNavigationRenderer::__toString() must not throw an exception, caught Error: Call to undefined method Icinga\Data\Db\DbConnection::getConfig()
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
    Fehler
Uncaught Error: Call to undefined method Icinga\Data\Db\DbConnection::getConfig() in /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php:704
Stack trace:
#0 /usr/share/php/Icinga/Data/SimpleQuery.php(122): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->init()
#1 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(300): Icinga\Data\SimpleQuery->__construct(Object(Icinga\Data\Db\DbConnection), Array)
#2 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(53): Icinga\Module\Monitoring\Backend\MonitoringBackend->query('HostStatus', Array)
#3 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(255): Icinga\Module\Monitoring\DataView\DataView->__construct(Object(Icinga\Module\Monitoring\Backend\Ido\IdoBackend), Array)
#4 /usr/local/share/icingaweb2/modules/graphite/application/controllers/ListController.php(42): Icinga\Module\Monitoring\Backen
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

after i disable the monitoring module the error does not raised but no monitoring available

can you help me to analyse the error?

what can i do?

thanks & regards
christian

**Comment by bebehei** [comment]
Which image do you use? When was this the image?

**Comment by christianuhlmann** [comment]
Tag latest, pulled from docker hub today:
https://hub.docker.com/r/jordan/icinga2/builds/bg5frbqmhmdhw4qbvesgmdi/

**Comment by bebehei** [comment]
@jjethwa I think we actually should remove this hack:

https://github.com/jjethwa/icinga2/blob/465bebe9245359eb479fd306ca88be605858da5d/Dockerfile#L69-L72

It got introduced right from the beginning in 7d066a2, but there is no note, **why** it was (or maybe still is) necessary.

An alternative could be a solution to #137 and tagging the modules to some proper gitrefs (not just master).

**Comment by jjethwa** [comment]
@bebehei 

Sounds good!  I'm back from vacation tomorrow and can take a look.  The hack was added as there was a problem with the first few Deb packages and versioned releases of the modules.  Should be fixed by now hehe
