### ISSUE TITLE
Access denied to mysql

### ISSUE THREAD

**Issue by hansij66** [jjethwa/icinga2#158]
Hi All

I took pretty much the plane vanilla docker image from today's master & docker-compose.

I get the following error:
.....
icinga2-master | ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.2' (using password: NO)
icinga2-master | run-parts: /opt/setup/50-icinga2 exited with return code 1
icinga2-master exited with code 1

The mariadb container does start (and graphite too if I enable this one); icinga2 bails out; I did add my passwords to secrets_sql.env.

Any hints were to look?

**Comment by jjethwa** [comment]
Hi @hansij66 

Are you able to connect to the mariadb container using the root credentials from the icinga2 container using the mysql CLI?

**Comment by hansij66** [comment]
Hi; thanks for the question, it helped to debug a bit further.
1) The Icinga2 container is not running - as the setup fails
2) I can docker exec -it into the mariadb container, and successfully login in mariadb: mysql -u root -p
3) I opened in the mariadb container 3308-->3306 to the host; I cannot login from docker host.
From host: mysql -h 172.19.0.3 -P 3308 -u root -p
ERROR 2003 (HY000): Can't connect to MySQL server on '172.19.0.3' (111 "Connection refused")

4) From mariadb container:
MariaDB [(none)]> SHOW GRANTS;
| Grants for root@localhost                                                                                                              |
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY PASSWORD '*****-deleted-****' WITH GRANT OPTION |
| GRANT PROXY ON ''@'%' TO 'root'@'localhost' WITH GRANT OPTION                                                                          

MariaDB [(none)]> SHOW GRANTS FOR root;
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY PASSWORD '*****-deleted-****' WITH GRANT OPTION |

This seems fine (??) although access is denied from a remote host? 

5) I looked into the setup files (/opt/setup/50-icinga2) - there access is limited to localhost? To be fair, I could not completely decipher all logic in the setup files....

For completeness - my docker-compose and secrets file; Thanks for any suggestions
docker-compose.yml:
version: '3'
services:
  icinga2:
    image: jordan/icinga2
    restart: on-failure:5
    container_name: icinga2-master

    container_name: icinga2-master
    hostname: icinga
    domainname: *********.com

    env_file:
      - secrets_sql.env
    environment:
      - ICINGA2_FEATURE_GRAPHITE=0
      - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
      - ICINGA2_FEATURE_GRAPHITE_PORT=2003
      - ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
      - DEFAULT_MYSQL_HOST=mysql
    volumes:
      - ./data/etc/icinga2:/etc/icinga2
      - ./data/etc/icingaweb2:/etc/icingaweb2
      - ./data/icinga2/lib/icinga:/var/lib/icinga2
      - ./data/icinga2/lib/php/sessions:/var/lib/php/sessions
      - ./data/icinga2/log/apache2:/var/log/apache2
      - ./data/icinga2/log/icinga2:/var/log/icinga2
      - ./data/icinga2/log/icingaweb2:/var/log/icingaweb2
      - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
    ports:
      - 127.0.0.1:1234:80
      - 192.168.1.1:5665:5665
  mysql:
    image: mariadb:10.1
    container_name: mysql-icinga2
    env_file:
      - secrets_sql.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./data/icinga2/log/mysql:/var/log/mysql

secrets_sql.env
ICINGA_WEB_PASSWORD=password1
DIRECTOR_API_PASSWORD=password2
ICINGAWEB2_ADMIN_USER=user1
ICINGAWEB2_ADMIN_PASS=password3
ICINGA2_USER_FULLNAME=Icinga2-svr
ICINGA2_FEATURE_DIRECTOR_PASS=password4
MYSQL_PASSWORD=password5
MYSQL_ROOT_PASSWORD=password6

**Comment by jjethwa** [comment]
Thanks for all of the information, @hansij66 

I think this might be an easy fix if my hunch is correct.  By default, the database root account is locked to access via localhost only.  You need to grant permission: https://mariadb.com/kb/en/library/configuring-mariadb-for-remote-client-access/#granting-user-connections-from-remote-hosts

**Comment by hansij66** [comment]
Hi, thanks for prompt response.

I was thinking the same, but out of the box, this is the priviliges setting of root

MariaDB [(none)]> SELECT User, Host FROM mysql.user ;
+------+-----------+
| User | Host      |
+------+-----------+
| root | %         |
| root | localhost |
+------+-----------+

Which seems ok to me (??)

I did add explicitly the ip address of the host (192.168.1.1); it does help to login from host - per link your provided
GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.1.1' IDENTIFIED BY 'root password' WITH GRANT OPTION;
FLUSH PRIVILEGES;

It does not fix logging in from the host.

One question before I continue to debug;
As last experiment, I did really take the stock docker-compose.yml from master branch (2f22974  on Mar 20); the only change I made was port 1234-->80 mapping.

Still same issue. Hence question, have you tested the latest docker-compose.yml with your latest icinga2 image; in a clean/empty configuration?

Happy to debug further & help, while it would help me if I know whether the docker-compose.yml works on a clean install.

Thanks! Hans

**Comment by hansij66** [comment]
Hi,
In the meantime I am able to connect to MariaDB from docker host; I made an error on my side; Hence that part works. Still, original problem remains

icinga2_1   | ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.3' (using password: NO)
icinga2_1   | run-parts: /opt/setup/50-icinga2 exited with return code 1

Looking at the error message, it states that "using password:NO"...but I did specify MYSQL_ROOT_PASSWORD is the secrets file.

One problem gone; still one to go.
Thanks. Hans

**Comment by hansij66** [comment]
I think I got it resolved. MYSQL_ROOT_PASSWORD  started with a "#"...That seems to work fine for setting up the initial database - as I can login using the password, but it seems to fail at some other places in the setup scripts. Probably interpreted as a comment?

Hard to figure out....but gladly that I got it to work.

Cheers Hans

**Comment by jjethwa** [comment]
That's great news, @hansij66 :smiley:   Having "#" would definitely break things as special handling would need to be added to escape it.
