### ISSUE TITLE
Question on Graphite - how to get it to work.

### ISSUE THREAD

**Issue by hansij66** [jjethwa/icinga2#159]
Hi,
Looking at issue #114 - which is still open (?)
I am using pretty much the stock docker-compose.yml from jjethwa/icinga2;
However, I don't get any graphs in Icingaweb2; Either I get "No Data" or "No Graphs found"
If I browse directly to the graphite container, I do get graphs...

Before I start digging, should it work out of the box (looking at #114 ) and if yes, any suggestion where to start?

I can ping graphite from icinga2 container.

Cheers
Hans

**Comment by bebehei** [comment]
Well, I admit my docker container on dockerhub is broken. I won't fix the `bebehei/graphite` docker container anymore.

I'd appreciate, if anyone volunteers and fixes the `docker-compose.yml` file to replace the current non-working graphite docker container.

IIRC there's an official graphite container in the meantime and if I guess right, the old one can get replaced quite easily with this one.

**Comment by hansij66** [comment]
I will give it a try....will be a bit low priority...summer holidays. I will post if I am successfull

**Comment by jjethwa** [comment]
Thanks @bebehei and @hansij66 

Looking at the official image: https://github.com/graphite-project/docker-graphite-statsd  I think it shouldn't be too bad to switch it in, just need to make sure the volumes map correctly.

**Comment by hansij66** [comment]
This works for me: (I am not an expert in github - feel free to add to master)

  graphite:
    image : graphiteapp/graphite-statsd
    container_name: graphite
    hostname: graphite

    volumes:
    - ./etc/graphite:/opt/graphite/conf
    - ./data/graphite/storage:/opt/graphite/storage
    - ./data/graphite/log/graphite:/var/log

**Comment by jjethwa** [comment]
Thanks @hansij66   I'll put the changes in for you 😄
