### ISSUE TITLE
Error using SNMP Plugins

### ISSUE THREAD

**Issue by tobizwetz** [jjethwa/icinga2#162]
Hey,
when I try to run a SNMP Plugin in bash, I get an Error from IPv4.pm
So when I run one of these:
`perl check_snmp_load.pl -H <RouterIP> -C <CommunityString> -w 5 -c 5`
` perl check_iftraffic.pl -H <RouterIP> -i GigabitEthernet0/1/2 -b 1 -u g -C <CommunityString>`
I get the following Error:
`usage: $sock->socket(DOMAIN, TYPE, PROTOCOL) at /usr/share/perl5/Net/SNMP/Transport/IPv4.pm line 36.`

Is anyone having an Idea?

Regards
Tobi

**Comment by bebehei** [comment]
http://lmgtfy.com/?q=usage%3A+%24sock-%3Esocket(DOMAIN%2C+TYPE%2C+PROTOCOL)+at+%2Fusr%2Fshare%2Fperl5%2FNet%2FSNMP%2FTransport%2FIPv4.pm+line+36.

**Comment by tobizwetz** [comment]
Thanks .... ;)
I already found that before:
https://github.com/dnsmichi/manubulon-snmp/issues/11

But I had to create the etc/protocols file (instead of etc/protocol) 
Now it works
