### ISSUE TITLE
Mail notification

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#17]
Hello, 

Nice work ! :+1: 

I just wanted to know, do you know how to make the mail notifications works ?

Thank you !

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Thank you :)   Since it's running inside a container, the SMTP daemon is not running.   You should create your own notification shell script (and related icinga2 configs)  to send email via the host that the container is running on or a relay server.   I set ours up to send notifications to Slack, so I can share that with you if needed :)

**Comment by Quentinvarquet** [comment]
Hello @jjethwa. Thank you for your answer.

I will try to find a solution for the mail notification (it's something very important for me).

Yes, i used slack for some projects, i would like to try if it's possble. You should add it in your github repo, it will help many users like me !

Thank you

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Here you go :)  https://github.com/jjethwa/icinga2-slack-notification

**Comment by Quentinvarquet** [comment]
Perfect, thank you !

**Comment by jjethwa** [comment]
NP at all.  Let me know if you have any questions and feel free to close the issue when you're ready :)

**Comment by Quentinvarquet** [comment]
Hello,

I just tried it. 

- I created a new incoming webhook. I tried it on my server with 

                      * curl -X POST --data-urlencode 'payload={"text": "This is post to <#alerts> and comes from *monkey-bot*.", "channel": "#si", "username": "monkey-bot", "icon_emoji": ":monkey_face:"}' https://hooks.slack.com/services/MY_SLACK_WEBHOOK_PATH

It works i can see the message in my channel.

- I added the slack-service-notification.sh to /etc/icinga2/scripts directory and i configured it like this : 

ICINGA_HOSTNAME="myserverip"
SLACK_HOSTNAME="hooks.slack.com"
SLACK_CHANNEL="#alerts"
SLACK_BOTNAME="icinga2"

I updated : 

curl --connect-timeout 30 --max-time 60 -s -S -X POST --data-urlencode "${PAYLOAD}" https://${SLACK_HOSTNAME}/services/<SLACK_WEBHOOK_PATH>

with 

curl --connect-timeout 30 --max-time 60 -s -S -X POST --data-urlencode "${PAYLOAD}" https://${SLACK_HOSTNAME}/services/**MY_SLACK_WEBHOOK_PATH**

- I added the contents of slack-service-notification.conf to my templates.conf 
- I added an entry to my notifications.conf (like in the readme).

I restarted icinga service. I tried to put off one serevr that is in my host.conf. When Icinga put it Red because it can't ping it, i don't egt any message in slack.

Do you have an idea ? 

Thank you :)

**Comment by Quentinvarquet** [comment]
Hello, (take your time for answer it's not important ;-)) 

I added the custom variable in my host.cfg : 

**vars.sla = "24x7"**

But the thing is, when I do e checkconfig before a restart of Icinga, I have this error  :+1: 



critical/config: Error: Validation failed for object 'Test Host!ssh!slack' of type 'Notification'; Attribute 'command': Object 'slack-service-notification' of type 'NotificationCommand' does not exist.
Location:
/etc/icinga2/conf.d/templates.conf(72):
/etc/icinga2/conf.d/templates.conf(73): template Notification "slack-service-notification" {
/etc/icinga2/conf.d/templates.conf(74):   command = "slack-service-notification"
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/templates.conf(75):
/etc/icinga2/conf.d/templates.conf(76):   states = [ OK, Warning, Critical, Unknown ]

critical/config: 2 errors
checking Icinga2 configuration. Check '/var/log/icinga2/startup.log' for details. ... failed

Do you have an idea ?

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

I just updated the script to make the Webhook URL easier to configure at the top part of the script.  I also forgot to add one more config file: slack-service-notification-command.conf  I've added it to the git repo.  Please add the contents of that file to your commands.conf (or keep it separate).  That should do the trick :)

**Comment by Quentinvarquet** [comment]
Hello, It works :-)

I had to had something in your files.

Here is my hosts.conf : 


object Host "[TILDE] Serveur KS" {
  import "generic-host"
  address = "My Ip"
  vars.os = "Debian 8.0"
  vars.sla = "24x7"
  vars.notification["slack"] = {
  	groups = [ "icingaadmins" ]
 			      }
}

But when i did a checkconfig à had this error : 

**critical/config: Error: Validation failed for object '[TILDE] Serveur KS!ssh!slack' of type 'Notification': Validation failed: No users/user_groups specified.**

So i added in notificication.conf :+1: 
**user_groups = host.vars.notification.slack.groups**

So it looks like : 

apply Notification "slack" to Service {
  import "slack-service-notification"
  user_groups = host.vars.notification.slack.groups
  interval = 10m
  assign where host.vars.sla == "24x7"

And after this it works.

Thank you for your time and your work !

**Comment by jjethwa** [comment]
Thank you!  Sorry, I had set this up a few months ago and forgot all the steps hehe.  We have a slightly different setup as we want separate notifications into different groups.  

I had created a user and usergroup in users.conf

```
object User "prod_alerts" {
  import "generic-user"

  display_name = "prod alerts"
  groups = [ "oncall" ]
  states = [ OK, Warning, Critical ]
  types = [ Problem, Recovery ]

  email = "my@email.com"
}

object UserGroup "oncall" {
  display_name = "oncall"
}
```

then in notification.conf I had

```

apply Notification "slack" to Service {
  import "slack-service-notification"
  user_groups = [ "oncall" ]
  interval = 30m
  assign where host.vars.sla == "24x7"
}
```

I'll update the readme.  Thanks again :)

**Comment by Quentinvarquet** [comment]
Thank to you for your help **and** your work !

I close the issue :)

**Comment by Quentinvarquet** [comment]
Hello, 

I will not reopen the issue don't worry ! :-) 

Did you know if someone found a solution to make the mail notification works from docker container ? 

Thank you

**Comment by jjethwa** [comment]
One of the previous PRs included the ssmtp and mailutils packages, so you should just need to configure things.  Here is a document that might be helpful :)

https://wiki.debian.org/sSMTP
