### ISSUE TITLE
Unable to monitor host which runs this container

### ISSUE THREAD

**Issue by TerrorSquad** [jjethwa/icinga2#171]
I'm having an issue setting up monitoring of the host server which runs this container.

The host is a CentOS 7 server, and Icinga 2 runs with the `docker stack deploy icinga2 --compose-file=docker-compose.yml` command. It is working beautifully, I've added a bunch of servers and it's monitoring them without a fault.

Now, I do not know how to monitor the host server. I've installed Icinga 2 on the host server, went through the `icinga2 node wizard`, gave it the IP address of the Icinga2 master which runs inside the docker container and port 5665. Now, if I go through the rest of the wizard and execute `service icinga2 reload` I will get an error from CentOS, saying that it cannot bind port `5665` to Icinga 2 service since it is already bound to Docker container inside Icinga 2 master server runs.

There are two more options which pop up during the `icinga2 node wizard`: Bind host [optional] and Bind port [optional].
I tried setting `Bind port [optional]` to `5666` and also, inside the Icinga 2 master (docker) setting the port variable inside the `/etc/icinga2/zones.d/master/docker-node-02.conf` file, inside the Endpoint object, but it's not working.

How can I set up this Icinga 2 docker solution to monitor its host?

**Comment by bebehei** [comment]
Your problem sounds to be absolutely a thing about mismatching ip and ports.

Given, that your other hosts work well, I assume your port forwarding on your docker host's interface IP and port is properly configured.

You have to tell your satellite (the icinga2 service, which is running on your docker host) to connect to its own interface IP on port `5665`, but also **listen** to its own interface IP, but then port 5666.

And your master (the icinga2 service, which is running inside your docker container) to connect to <interface ip>:5666.

I can't give you any further info. I don't know the specifics of your system. There may be a firewall involved or some other weird stuff.

Try to enter your docker container and then fire `wget` against the port of the icinga2 satellite service. `wget` should fail for some CA reasons. But at least then you know, the interconnection works.
