### ISSUE TITLE
Add icinga2 web2 modules

### ISSUE THREAD

**Issue by aleliga** [jjethwa/icinga2#172]
Are there an easy way to add web2 modules to the container?
like the ones in https://icinga.com/products/icinga-web-2-modules/

Ale

**Comment by bebehei** [comment]
Just:

1. copy them into a folder in your docker host
1. mount the folder into your docker container
1. set the icingaweb's module path to the mounted folder of your container

That would be the easiest most straight forward way.

**Comment by bebehei** [comment]
IIRC, I've already added a default module path, which could get used in conjunction with the container.

You can use `/etc/icingaweb2/userModules`. This path is added by default and in this container and its purpose serves exactly your question.

**Comment by aleliga** [comment]
Thank you I'll try!
Alessio

**Comment by Henry78** [comment]
I don't know if this is connected, but the procedure to add modules ([Readme.md#adding-own-modules](https://github.com/jjethwa/icinga2#adding-own-modules)) doesn't work anymore. Please update the documentation.

**Comment by jjethwa** [comment]
Hi @Henry78 

Have you tried adding the module(s) to /etc/icingaweb2/userModules ?  If that does not work, please create a new issue.   Do you see an error in the Icinga Web 2 / Apache logs?  What module(s) are you trying to add?

**Comment by Henry78** [comment]
Sorry for the late replay. I don't have access to the system anymore and won't be able to reproduce the setup for the next few month.

**Comment by jjethwa** [comment]
Thanks, @Henry78 

Just report back when you can
