### ISSUE TITLE
roles.ini overwritten on restart

### ISSUE THREAD

**Issue by ontherunvaro** [jjethwa/icinga2#176]
As the title says, `/etc/icingaweb2/roles.ini` is overwritten with every container restart, thus losing configuration.

**Comment by jjethwa** [comment]
Hi @ontherunvaro 

Are you using a volume for /etc/icingaweb2 ?  If so, this section should catch that: https://github.com/jjethwa/icinga2/blob/master/content/opt/setup/60-icingaweb2#L17-L20

**Comment by ontherunvaro** [comment]
Yes I am (actually using the compose file from this repo), but actually I think [this line](https://github.com/jjethwa/icinga2/blob/9bb1ef88f74f0b97498ab4cceaa9b1a3958468e3/content/opt/setup/60-icingaweb2#L80) is the culprit. Only the Administrator group is rewritten, but it's okay if I just create a different admin group with a different name. I don't think this is worth "fixing" but maybe a line in the readme would be cool.

Thank you for your work!

**Comment by jjethwa** [comment]
Sounds good!  Thanks so much, @ontherunvaro  😄
