### ISSUE TITLE
Image rebuilds for new Icinga releases

### ISSUE THREAD

**Issue by magnusbaeck** [jjethwa/icinga2#177]
Right now a new image is built and pushed to Docker Hub when a new commit is pushed to GitHub, but unless that happens sufficiently often the available tagged images (https://hub.docker.com/r/jordan/icinga2/tags) will lag behind.

As of March 19, 2019, Icinga 2.10.4 is the most recent version of Icinga yet only 2.10.2 is available on Docker Hub. The image tagged "latest" was built after the release of 2.10.3 so I'd expect it to contain 2.10.3, but if so my question would be why that image hasn't also been tagged 2.10.3.

So I guess my question is, why is there no 2.10.3-tagged image despite that release predating the most recent commit by three weeks, and is there a way to automate image builds in a way so that Icinga releases are made available faster? From a quick look at the Docker Hub documentation push-triggered builds seems to be the only option.

**Comment by jjethwa** [comment]
Hi @magnusbaeck 

Sorry about that.  I ran into an issue with the new version of Docker Hub and have opened a ticket with them.  There is a workaround, so I am doing that now.  2.10.3 and 2.10.4 are tagged and available now.

**Comment by magnusbaeck** [comment]
Great, thanks!

**Comment by magnusbaeck** [comment]
Any movement on the Docker Hub ticket you filed? If not, could I trouble you to employ the workaround for the 2.10.5 release as well?

**Comment by jjethwa** [comment]
Hi @magnusbaeck 

Unfortunately, no movement yet.  I'll ping them again.  I'll get that new release built and tested tomorrow.  Thanks :+1:

**Comment by jjethwa** [comment]
Hi @magnusbaeck 

2.10.5 is available now.  I'll let you know if there's movement on the ticket.  Thanks again!
