### ISSUE TITLE
Graphite writer overwriting custom settings in volume mount

### ISSUE THREAD

**Issue by EdJoJob** [jjethwa/icinga2#182]
To Reproduce:

1. Start container with `/etc/icinga2` as a volume and `ICINGA_FEATURE_GRAPHITE=1`
2. Edit `/etc/icinga2/features-enabled/graphite.conf` to add ` enable_send_metadata = true`
3. Stop container
4. Start new container
5. Observe that edit to `/etc/icinga2/features-enabled/graphite.conf` was not persisted

Proposed solution:
Only create the `/etc/icinga2/features-enabled/graphite.conf` if it does not already exist in `/opt/setup/51-icinga2-graphite`

**Comment by jjethwa** [comment]
Thanks for reporting the issue, @EdJoJob 

Would you like to submit a PR?  Thanks :smile:

**Comment by EdJoJob** [comment]
I will be able to get something sorted for it.

There is a concern if we change `ICINGA_FEATURE_GRAPHITE_HOST` and `ICINGA_FEATURE_GRAPHITE_PORT` environment which will not be reflected in the new container should we not do rewrites.

Or should we add two more environment variables:

* `ICINGA_FEATURE_GRAPHITE_SEND_THRESHOLDS` default `true`
* `ICINGA_FEATURE_GRAPHITE_SEND_METADATA` default `false`

**Comment by jjethwa** [comment]
Thanks, @EdJoJob 

I think the latter option would allow users a bit more flexibility with their configuration.

**Comment by jjethwa** [comment]
@EdJoJob 

Build is queued in Docker Hub.  It should be available within the next 30 - 45 mins hopefully.  Appreciate your PR 😄
