### ISSUE TITLE
No way to add custom CA-certificates for `check_http`

### ISSUE THREAD

**Issue by EdJoJob** [jjethwa/icinga2#185]
When using an internal custom CA for service certificates there is no method to include these in the CA store.  This may cause issues with `check_http` as per https://support.nagios.com/forum/viewtopic.php?f=7&t=39237

I would propose having a new script in `/opt/setup` to add certs to the CA bundle using the method at https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html where we mount a volume at `/usr/local/share/ca-certificates`

**Comment by jjethwa** [comment]
Hi @EdJoJob 

You should be able to use /etc/ssl as a volume when starting the container, is that not working for you?

**Comment by EdJoJob** [comment]
Not when my host OS is CentOS which bundles all the certs into a single PEM.
Where Debian authorises multiple certificates in separate files (from what I understand, I don't have the same experience with Debian based systems)

**Comment by bebehei** [comment]
I guess, we should add another script like #184 did it. It might be necessary only to cope with a special use case. But a few lines should suffice.

**Comment by jjethwa** [comment]
Hi @EdJoJob 

Would you like to submit a PR for this?  Thanks 😄
