### ISSUE TITLE
status.cgi

### ISSUE THREAD

**Issue by Gibby** [jjethwa/icinga2#19]
Any ideas how to get this working with the Icinga Status extension for chrome? https://github.com/kepi/IcingaChromedStatus

**Comment by jjethwa** [comment]
Hi @Gibby 

I haven't used that extension and it looks like it might be in need of an update.  You can try to see if it works with Icinga2's Livestatus feature: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/alternative-frontends#setting-up-livestatus

**Comment by jjethwa** [comment]
Marking as closed since it's been a while without a response
