### ISSUE TITLE
Replace ssmtp with msmtp

### ISSUE THREAD

**Issue by svenakela** [jjethwa/icinga2#195]
As ssmtp is unmaintained and msmtp is active, it would be a better choice to switch. 
With msmtp Gmail relaying works, with ssmtp not so much.

**Comment by jjethwa** [comment]
Thanks for the heads up, @svenakela   Would you like to submit a PR for this? 😄

**Comment by svenakela** [comment]
A bit busy this week but can sure look into it later on.

**Comment by svenakela** [comment]
I have a working update. I just need to figure out why e-mails to `root@localhost` are sent out instead if being forwarded to the `root` alias in the aliases file. Sending messages to `root` works as expected though.

**Comment by jjethwa** [comment]
Thanks @svenakela  Looking forward to it.  Much appreciated!

**Comment by svenakela** [comment]
I got an answer about the `@localhost` from the author himself of msmtp. Any address with an @-sign will be assumed to not be local. It all makes sense but it also means there is a minor change that has to be done in the `users.conf`. 

But... ...I also took this far longer than I planned. I upgraded everything to latest Debian and had to make quite a lot of changes to the Dockerfile to make Icinga run out-of-the-box. I will make a Pull Request as soon as I have tested the last changes.

**Comment by jjethwa** [comment]
Thanks so much, @svenakela   I've been thinking about doing the Debian upgrade myself, but remembered how much work it was with the past few upgrades, so I have been putting it off a bit.  Really appreciate all of your effort 😄

**Comment by jjethwa** [comment]
Thanks @svenakela 
Just made two minor modifications and things are working great!  Grab a copy of latest and check it out.  Really appreciate all of your work!

**Comment by svenakela** [comment]
Done deal!
