### ISSUE TITLE
Update Docker Container not working

### ISSUE THREAD

**Issue by GrexAut** [jjethwa/icinga2#196]
Hello,

I'm trying to update from Docker Container with icinga2 Version r2.8.2-1 to the latest (2.11.0).
I deleted the docker container, and try to start with latest icinga2 docker image.
I using linked volumes and external mysql server, but I get an error, my output is:

```
Site 000-default already enabled
Site icingaweb2-ssl already disabled
Site icingaweb2-ssl-redirect already disabled
Pinging mariadb:3306
warning/cli: Feature 'ido-mysql' already enabled.
warning/cli: Feature 'livestatus' already enabled.
warning/cli: Feature 'compatlog' already enabled.
warning/cli: Feature 'command' already enabled.
warning/cli: Feature 'graphite' already disabled.
Pinging mariadb:3306
Found invalid module in enabledModule directory "/etc/icingaweb2/enabledModules": "/etc/icingaweb2/enabledModules/monitoring" points to non existing path "false"
Found invalid module in enabledModule directory "/etc/icingaweb2/enabledModules": "/etc/icingaweb2/enabledModules/doc" points to non existing path "false"
Launching the run script /usr/local/share/icingaweb2/modules/director/run.php for module director failed with the following exception: Missing dependencies, please check
Module path "/etc/icingaweb2/userModules" does not exist
ERROR: Icinga\Exception\ConfigurationError in /usr/share/php/Icinga/Application/Modules/Manager.php:248 with message: Cannot enable module "monitoring". Module is not installed.
run-parts: /opt/setup/60-icingaweb2 exited with return code 1
```

my start command is:
```
docker run --name icinga2
-h myHostname
-v icinga2_ssmtp_config:/etc/ssmtp
-v icinga2_icinga2_config:/etc/icinga2
-v icinga2_icingaweb2_config:/etc/icingaweb2
-v icinga2_data:/var/lib/icinga2
-v icinga2_log:/var/log
-v icinga2_icingaweb2_share:/usr/share/icingaweb2
-v icinga2_nagios:/usr/lib/nagios
-v /etc/protocols:/etc/protocols
--link mariadb_icinga2:mariadb
-e DEFAULT_MYSQL_HOST=mariadb
-e DEFAULT_MYSQL_USER=root
-e DEFAULT_MYSQL_PASS=XXX
-e MYSQL_ROOT_PASSWORD=XXX
-e TZ=Europe/Vienna
-p SECONDIP:80:80
-p SECONDIP:443:443
-p SECONDIP:5665:5665
--net myNetwork
--ip MYIP
-t jordan/icinga2
```

any ideas?

**Comment by aleliga** [comment]
You are mounting icinga2_icingaweb2_config:/etc/icingaweb2
Probably there isn't the /enabledModules subdirectory
Try to take a look in the host directory icinga2_icingaweb2_config or excluding this mount

**Comment by GrexAut** [comment]
Hi, this is my content of icinga_icingaweb2_config volume on docker host:

> ls -l /var/lib/docker/volumes/icinga2_icingaweb2_config/_data/
total 40
-rw-r--r-- 1 www-data systemd-network  379 May  2 15:09 announcements.ini
-rw-r--r-- 1 www-data systemd-network  338 Apr 23  2018 authentication.ini
-rw-r--r-- 1 www-data systemd-network  309 Apr 30  2018 config.ini
-rw-r--r-- 1 www-data systemd-network    0 Feb 26  2018 CONFIGURED
drwxrws--- 7 www-data systemd-network 4096 Sep 19 15:34 dashboards
drwxr-xr-x 2 www-data systemd-network 4096 Feb 26  2018 enabledModules
-rw-r--r-- 1 www-data systemd-network   54 Feb 26  2018 groups.ini
drwxr-xr-x 6 www-data systemd-network 4096 Feb 26  2018 modules
-rw-r--r-- 1 www-data systemd-network  722 May  2 15:09 resources.ini
-rw-r--r-- 1 www-data systemd-network  705 Jun 15  2018 resources.ini.bk
-rw-r--r-- 1 www-data systemd-network 1237 Sep 19 16:09 roles.ini

And this is my enabledModules folder:

> ls -l /var/lib/docker/volumes/icinga2_icingaweb2_config/_data/enabledModules/
total 0
lrwxrwxrwx 1 www-data systemd-network 44 Feb 26  2018 director -> /usr/local/share/icingaweb2/modules/director
lrwxrwxrwx 1 www-data systemd-network 39 Feb 26  2018 doc -> /usr/local/share/icingaweb2/modules/doc
lrwxrwxrwx 1 www-data systemd-network 46 Feb 26  2018 monitoring -> /usr/local/share/icingaweb2/modules/monitoring


The error message" Cannot enable module "monitoring". Module is not installed" comes from icinga2, isn't it?

**Comment by GrexAut** [comment]
Ok, found the solution, my fault was, to make a volume mapping of /usr/share/icingaweb2
I removed "-v icinga2_icingaweb2_share:/usr/share/icingaweb2" and worked.
But now I have the problem, that for the director module, the depended modules (ipl, reactbundle, incubator) are not installed.
