### ISSUE TITLE
Container keeps overwriting /etc/icinga2/zones.conf at startup

### ISSUE THREAD

**Issue by sven-borkert** [jjethwa/icinga2#199]
When restarting the container, it keeps overwriting the zones.conf file each time, making me loose all the zones configuration. The container only adds himself as the master zone and "global-templates" and "director-global". 

/*
 * Generated by Icinga 2 node setup commands
 * on 2019-10-08 08:17:14 +0000
 */

/etc/icinga2 is mounted as a volume

Image is: sha256:38ca6087e7c5c549f2a10f4f54defe9feca3aef750fceb7f76fdf5d5c6ccf9b4

Why does it do this, and how do I stop this? I have a second installation of this image, and it does not rewrite the zones.conf at every restart. I don't see the difference here. 

Regards,
Sven

**Comment by jjethwa** [comment]
Hi @sven-borkert 

Sorry to hear about the issue.  My guess is that it's https://github.com/jjethwa/icinga2/blob/master/content/opt/setup/50-icinga2#L39-L41 that is doing it due to the container name change.  Is there a difference between how you are running the containers?  Docker args, etc

**Comment by sven-borkert** [comment]
Hi Jordan,

thank you, that's just what I was looking for. The hostname of the container is not matching the "NodeName" in constants.conf. 

Hostname is short, but NodeName is FQDN. So it checks for <short hostname>.key and calls the node setup. The actual key is <fqdn hostname>.key.

The container without the problem is just named "icinga", and there was an "icinga.key" file existing, so it just did not call the node setup. 

Regards,
Sven

**Comment by jjethwa** [comment]
Thanks, Sven.

If you have any suggestions for documentation, etc let me know 😄  Also, let me know if we can close the ticket.  Thanks again.

**Comment by sven-borkert** [comment]
Hi Jordan,

thank you, I'll close the issue.

Regards,
Sven
