### ISSUE TITLE
MySQL server failed on starting using host volume

### ISSUE THREAD

**Issue by zijam** [jjethwa/icinga2#2]
I have taken a backup of all the volume and located them on host machine, but when I try to start up a new instance with the backup data, the MySQL database won't startup.
```
 mini:~ siyalrach$ docker run -t -v /Users/siyalrach/Desktop/icinga/etc/icinga2:/etc/icinga2 -v /Users/siyalrach/Desktop/icinga/etc/icinga-web:/etc/icinga-web -v /Users/siyalrach/Desktop/icinga/var/lib/mysql:/var/lib/mysql -h jicinga.level8.com jordan/icinga2:latest
 Symlink for /etc/icinga2/features-enabled/ido-mysql.conf exists already...skipping>  Symlink for  /etc/icinga2/features-enabled/livestatus.conf exists already... skipping
  Symlink for /etc/icinga2/features-enabled/compatlog.conf exists already... skipping
  Symlink for /etc/icinga2/features-enabled/command.conf exists already...skipping
  =>Initializing databases and icinga2 configurations.
  =>This may take a few minutes
  [FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!
```

**Comment by zijam** [comment]
I'm running OSX Yosemite using Boot2Docker

**Comment by jjethwa** [comment]
Hi @zijam 

When starting your new container using the restored data, are you starting it with passwords that were generated (or passwords you supplied) with the original container? You will need to provide these passwords at the minimum: ICINGA_PASSWORD , ICINGA_WEB_PASSWORD , IDO_PASSWORD You can check the docker logs for the old container to find the passwords that were set or provided.  Please let me know if that helps.  Thanks :)

**Comment by zijam** [comment]
Still same error:

> mini:icinga2 siyalrach$ docker run -p 80:80 -t -e ICINGA_PASSWORD="icinga" \
> -e ICINGA_WEB_PASSWORD="icinga" -e IDO_PASSWORD="icinga" \
> -e DEBIAN_SYS_MAINT_PASSWORD="icinga" jordan/icinga2:latest
> =>Initializing databases and icinga2 configurations.
> =>This may take a few minutes
>  [ ok ] Starting MySQL database server: mysqld ..
>  [info] Checking for tables which need an upgrade, are corrupt or were 
not closed cleanly..
> [ ok ] Stopping MySQL database server: mysqld.
> '==================================================================='
>MySQL user 'root' has no password but only allows local connections
>MySQL user 'debian-sys-maint' password set to 8qTtwFLGvYL6ilJ
>MySQL user 'icinga' password set to icinga
>MySQL user 'icinga2-ido-mysq' password set to icinga
>MySQL user 'icinga-web' password set to icinga
>'==================================================================='
>Starting Supervisor.  You can safely CTRL-C and the container will continue to run with or without the -d (daemon) option

My backup script, using it after I have stopped all services on the container
>docker run --rm --volumes-from $CONTAINER_NAME -v $(pwd):/backup busybox tar cvf /backup/$VOLUME_BACKUP_NAME.tar $VOLUME_NAME

After I have untar the volume on my host machine I run this command

> mini:icinga siyalrach$ docker run -p 81:80 -t -v /Users/siyalrach/Desktop/icinga/etc/icinga2:/etc/icinga2 \
>-v /Users/siyalrach/Desktop/icinga/etc/icinga-web:/etc/icinga-web \
> -v /Users/siyalrach/Desktop/icinga/var/lib/mysql:/var/lib/mysql \
> -e ICINGA_PASSWORD="icinga" -e ICINGA_WEB_PASSWORD="icinga" \
> -e IDO_PASSWORD="icinga" -e DEBIAN_SYS_MAINT_PASSWORD="8qTtwFLGvYL6ilJ" \
> jordan/icinga2:latest
> Symlink for /etc/icinga2/features-enabled/ido-mysql.conf exists already...skipping
> Symlink for /etc/icinga2/features-enabled/livestatus.conf exists already... skipping
> Symlink for /etc/icinga2/features-enabled/compatlog.conf exists already... skipping
> Symlink for /etc/icinga2/features-enabled/command.conf exists already...skipping
> =>Initializing databases and icinga2 configurations.
> =>This may take a few minutes
> [FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!

**Comment by jjethwa** [comment]
Hi @zijam 

Really appreciate your thoughtful comments as you're providing a lot of information for me to work on :)  I was able to reproduce the issue.  MySQL was unable to start up due to file ownership issues.  I will make changes to the run script so the container chowns the volume data before attempting to write to it.

Once the ownership problem was fixed, I ran into another issue.  The run command tries to set up the schema and errors out as it exists already.  I am going to make changes to ignore the error but keep in mind that you may need to update the schema if you are upgrading to a newer version of Icinga2 (Link: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/getting-started#upgrading-mysql-db )

I will make the changes, validate, and let you know when the new container is ready to be pulled.  Thanks again,

Jordan

**Comment by jjethwa** [comment]
@zijam 

Please try pulling the latest container.  I cannot reproduce the issue now.  If it works for you, please let me know and close the issue.  Really appreciate you logging the issue and helping me through it.  Thanks,

Jordan

**Comment by zijam** [comment]
Still have the same problem, I have also tried with a data-only container

```
# Dockerfile
FROM busybox

VOLUME ["/var/lib/mysql"]

CMD ["/bin/sh"]
```

and started with the volumes-from command
```
docker run -t -i --volumes-from mysql_data level8/icinga2
```

**Comment by jjethwa** [comment]
Hi @zijam 

Can you try one test?  Can you try chmod -R 777 /Users/siyalrach/Desktop/icinga/var/lib/mysql  and see if that works.  The file ownership issues with volumes are a little hard to work with :(

**Comment by zijam** [comment]
It works with mysql, but now I'm unable view icinga2 in the brower
```
PDO Connection Error: SQLSTATE[28000] [1045] Access denied for user 'icinga_web'@'localhost' (using password: YES)
```

**Comment by zijam** [comment]
Log file from icinga2

```
root@f35824bbfca4:/# cat /var/log/icinga2/icinga2.log 
[2015-01-21 21:58:02 +0000] information/LivestatusListener: Created UNIX socket in '/run/icinga2/cmd/livestatus'.
[2015-01-21 21:58:02 +0000] information/ConfigItem: Activated all objects.
[2015-01-21 21:58:02 +0000] critical/IdoMysqlConnection: Connection to database 'icinga2idomysql' with user 'icinga2-ido-mysq' on 'localhost:3306' failed: "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)"
Context:
	(0) Reconnecting to MySQL IDO database 'ido-mysql'

[2015-01-21 21:58:02 +0000] critical/IdoMysqlConnection: Exception during database operation: Verify that your database is operational!
[2015-01-21 21:58:12 +0000] information/IdoMysqlConnection: MySQL IDO instance id: 1 (schema version: '1.12.0')
[2015-01-21 21:59:42 +0000] information/Application: Shutting down Icinga...
[2015-01-21 21:59:42 +0000] information/CheckerComponent: Checker stopped.
[2015-01-21 21:59:42 +0000] information/DbConnection: Pausing IDO connection: ido-mysql
[2015-01-21 22:00:47 +0000] information/ConfigItem: Activated all objects.
[2015-01-21 22:00:47 +0000] information/IdoMysqlConnection: MySQL IDO instance id: 1 (schema version: '1.12.0')
```

**Comment by jjethwa** [comment]
Hi @zijam 

Does it look like MySQL is running in the container?  It should be started automatically by supervisor.  Thanks for your patience,

Jordan

**Comment by zijam** [comment]
Hi @jjethwa 

MySQL is running in the container
```
root@f35824bbfca4:/# supervisorctl status
apache2                          RUNNING    pid 715, uptime 0:00:04
icinga2                          RUNNING    pid 16, uptime 0:00:45
mysql                            RUNNING    pid 15, uptime 0:00:45
```

```
mysql> show databases;  
+--------------------+
| Database           |
+--------------------+
| information_schema |
| icinga             |
| icinga2idomysql    |
| icinga_web         |
| mysql              |
| performance_schema |
+--------------------+
6 rows in set (0.04 sec)
```

**Comment by zijam** [comment]
Found a solution to the problem.

Boot2Docker for OSX have permissions problems with volumes https://github.com/boot2docker/boot2docker/issues/581

I used the docker image from svendowideit/samba https://github.com/SvenDowideit/dockerfiles/tree/master/samba to connect to the volume from the running container instance of jordan/icinga2, then I was able to mount the volumes in OSX without any permissions issues.

**Comment by jjethwa** [comment]
Thanks so much, @zijam   I was going crazy trying to figure out why the permissions were still having an issue :p
