### ISSUE TITLE
BUG : Backend icinga is not running

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#20]
Hello,

I am using your icinga container in production : v2.3.0-193-g3eb55ad (version 06/2015 if I have a good memory).

I have 1450 hosts with almost 1700 services.

Since 2 months I have a problem, every 2 or 3 weeks I have this error message in "System > Monitoring health" : **Backend icinga is not running**. Icinga services are not running anymore in the container.

The solution is to restart the container, but it's starting to be a big problem because we are using it in production.

Do you have a solution ? Is-it because I am using an "old" version of icinga2 ?

I just checked my log, i have this : 

[2015-11-18 20:26:41 +0100] information/Application: Got reload command: Starting new instance.
[2015-11-18 20:26:42 +0100] information/Application: Received request to shut down.
[2015-11-18 20:26:42 +0100] information/Application: Shutting down...
[2015-11-18 20:26:42 +0100] information/CheckerComponent: Checker stopped.
[2015-11-18 20:26:42 +0100] information/DbConnection: Pausing IDO connection: ido-mysql
[2015-11-18 20:26:42 +0100] critical/Socket: accept() failed with error code 9, "Bad file descriptor"
[2015-11-18 20:26:42 +0100] critical/ListenerListener: Cannot accept new connection.

Thank you very much

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

From the log entries, it looks like a reload command was issued, but when the new process was forked, it was unable to open the socket.  Usually, the old process stays running until the new one takes over completely.  It could be a bug in the version you are using.  Try upgrading :)

**Comment by Quentinvarquet** [comment]
Hello @jjethwa ,

Thank you for your answer.

We have a process that reload the conf every 10 minutes and sometimes after 3 weeks we have this problem. 

I think we will try to update our version.

Thanks for your time :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Why do you reload every 10 minutes?  Is it to see if there are new config file changes?  I'm not sure how you're deploying the changes, but you could probably script something with inotifywait to see if files have changes under volume directory that you are using as the /etc/icinga2 volume( for the container) and have that perform the reload for you?  If you're using git to store the config file changes, you could have a webhook from git to Jenkins then have Jenkins copy over the files and do a reload too.  Just a few ideas :)

**Comment by Quentinvarquet** [comment]
Hi @jjethwa 

We are using a configuration management database (working with postgresql) with all hosts (servers, network devices, ... almost 1500 hosts)

They all have a "LiveCycleStatus" in the cmdb (power off, in development, live).

We created a custom script in icinga that will check every 10 minutes in the postgresql database all hosts with the Status " Live ". Then the old conf files is deleted and a new one is created (even if we don't have any change).

It was the first step in our production we have to update it (for example the script don't delete the conf file if we don't have any change, this is the next step).


**If you're using git to store the config file changes, you could have a webhook from git to Jenkins then have Jenkins copy over the files and do a reload too**

I will check this solution !

**Just a few ideas :)**

Thank you very much :-)

**Comment by Quentinvarquet** [comment]
Hello, we just fix it by updating the conf file of the supervisor. 

In Icinga container : etc/supervisor/conf.d/icinga2.conf 

We just added a new line :

*autorestart=true* and icinga restart when it crash :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

That's right!  I forgot about that setting.  I think I left it off before as some people wanted to perform checkconfigs or stop it manually without supervisor starting it up again.

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Latest version of the container has autostart and also some fixes for supervisor

**Comment by Quentinvarquet** [comment]
Hello!

Thank you for the information.

We really have to update icinga,  we have an old version (may/June if I
have a good memory) and one week ago I tried the last version and many
things changed.

I will add this task in my to do list!

I guess I also have to update docker,  we are using version 1.6 :-)

Have a good day
