### ISSUE TITLE
Call to undefied function mb_strlen() - package php7.3-mbstring_7.3.9-1 is required

### ISSUE THREAD

**Issue by GrexAut** [jjethwa/icinga2#204]
Hello,

I get the following error in icingaweb2:
![grafik](https://user-images.githubusercontent.com/5990312/66756862-259e8c80-ee9b-11e9-99fb-3dea8d88cd71.png)

I installed the deb package, and it is working fine now (after apache2 restart)
https://packages.debian.org/buster/amd64/php7.3-mbstring/download

**Comment by jjethwa** [comment]
Hi @GrexAut  

Thanks for the issue.  Looks like you have the change added to your Dockerfile.  Want to send a PR over?  Thanks :smile:

**Comment by GrexAut** [comment]
Ups,... did PR now

**Comment by jjethwa** [comment]
Just merged, @GrexAut 

Thanks again :smiley:
