### ISSUE TITLE
MYSQL login access denied

### ISSUE THREAD

**Issue by Maxwell-Mc** [jjethwa/icinga2#208]
We are using icinga2's influxdbwriter to send our check results to a remote influx database and the issue we are having is when our tunnel goes down between our icinga2 instance and our influxdb. We need to look at our historical data from the icinga2 container stack from when our tunnel dies and our thought was to access the Mariadb to look at the data we are missing on our influxdb. However, when we try to access the Mariadb we are slapped with access denied from both the mysql container and the icinga2 container, as well as from the host PC. So how do access this historical data for our use outside of the icinga stack? 

Thank you!

**Comment by jjethwa** [comment]
Hi @Maxwell-Mc 

By default, MariaDB/MySQL only allows connections from localhost.  If you want to allow remote connections, you need to follow the directions here: https://mariadb.com/kb/en/library/configuring-mariadb-for-remote-client-access/

Let me know if that works 😄

**Comment by Maxwell-Mc** [comment]
JJethwa your're awesome, thank you for your quick responses always. We just misunderstood the format for our .env file and our password had <> symbols around it, which we did not know would become part of the password. 

have a good day!
