### ISSUE TITLE
check_ping 

### ISSUE THREAD

**Issue by x-sven** [jjethwa/icinga2#210]
Hi, I've got an error on the web interface with a fresh image: 
execvpe(/usr/lib/nagios/plugins/check_ping) failed: No such file or directory

**Comment by jjethwa** [comment]
Hi @x-sven 

Sorry for the late reply, just had small holiday here.  What version of the image are you using?  Latest?

**Comment by x-sven** [comment]
yes, the latest.

**Comment by jjethwa** [comment]
Hi @x-sven 

I just pulled the latest and do not see the issue.  Do you have any more details?

**Comment by x-sven** [comment]
I'm was pulling "jordan/icinga2:latest", then, the plugins below /usr/lib/nagios/plugins where incomplete. At least check_ping was missing. Installation via apt could not fix it. However, I've pulled the image, created a new container and it seems to work now. I have no idea was was going wrong. 

Cheers, Sven

**Comment by jjethwa** [comment]
Thanks for confirming, @x-sven :+1:
