### ISSUE TITLE
Please release a docker image tagged with 2.11.1 and 2.11.2

### ISSUE THREAD

**Issue by christian-weiss** [jjethwa/icinga2#219]
First of all i want to say: thank you for providing docker images.

Please release a docker image tagged with 2.11.1 and 2.11.2, as Icinga2 version 2.11.1 and 2.11.2 were released in oct. 2019.

**Comment by jjethwa** [comment]
Hi @christian-weiss 

Thanks!  Sorry, I've been really busy the past few months and not doing a good job and maintaining the tags and builds.  I've tagged 2.11.2 now.  Appreciate the reminder 😄
