### ISSUE TITLE
Icinga container is full

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#22]
Hello,

My icinga container is full..When I connect on my icinga interface I have this message : 

Server error: SQLSTATE[HY000]: General error: 1030 Got error 28 from storage engine.

If I connect inside my container and I check the disk storage : 

rootfs                                                                                             9.8G  9.3G  4.0K 100% /

Do you have any solution ? Thank you

**Comment by Quentinvarquet** [comment]
Ok, I solved it, it was the icinga log in /var/log/icinga2, I forgot it.

**Comment by gvenka008c** [comment]
@jjethwa @Quentinvarquet My container size is showing 80% full. I cleared the logs as well. Is there any other location that needs to be looked at?

---
icinga2]# ls -ltr
total 8
drwxr-x--- 2 icinga icinga    4096 Jun  3 13:41 crash
drwxr-x--- 3 icinga icingacmd 4096 Jun  3 13:41 compat
-rw-r--r-- 1 icinga icinga       0 Jun  6 08:06 icinga2.log

#df -h
/dev/vda1        20G   15G  4.0G  80% /

---

**Comment by Quentinvarquet** [comment]
Hello you can also check the mysql folder.

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Try to find out which directory is using up the space so we can help.  Also, it'll be better to open up a new issue to make it easier to track :)
