### ISSUE TITLE
Build multiarch docker images: provide an arm64v8 image

### ISSUE THREAD

**Issue by christian-weiss** [jjethwa/icinga2#220]
ARM is an important architecture, empowering clouds (like AWS; cost savings about 45% are possible on AWS with ARM), RaspberryPi and tons of NAS systems, etc.

Please provide a multiarch docker image that includes arm64/v8.

This would enable me to run icinga2 on my QNAP NAS, as my mariadb is already on this ARM device.

**Comment by christian-weiss** [comment]
It is as easy as running:
```
docker buildx build --platform linux/arm,linux/arm64,linux/amd64/v8 -t jordan/icinga2 . --push
```

Just follow the preparation steps described here:
https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

Supported platform names are here:
https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by christian-weiss** [comment]
graphiteapp/graphite-statsd is (since today) also a multiarch docker image (since version 1.1.6-2).
So the only missing docker image from your docker-compose.yml is icinga2 itself.

**Comment by jjethwa** [comment]
Hi @christian-weiss 

Thanks so much!  It's actually something I've been wanting to do and looks like it's a lot easier to do now.  I do all my builds using Docker Hub to assure people that it is a clean build environment, secure, etc.  I don't see an option to have Docker Hub to do multiarch builds though 😢

**Comment by christian-weiss** [comment]
I have seen people building multiarch (incl. ARM) images on Docker Hub Autobuilds. 
E.g. https://www.trion.de/news/2019/10/14/docker-multi-arch-dockerhub.html# (use google translate)
This example is with multiple Dockerfiles, which is no longer required. Maybe you can alter the idea (the hooks) to setup a qemu-based environment for:
``` 
docker buildx build --platform linux/arm,linux/arm64,linux/amd64/v8 -t jordan/icinga2 . --push
```

**Comment by jjethwa** [comment]
Great, thanks, @christian-weiss   That's the older method that dealt with manifest files and was a bit ugly.  I'll look into the new buildx method and see if there's a good place I can run that on.  Really appreciate it!

**Comment by christian-weiss** [comment]
For your information "graphiteapp/graphite-statsd" uses `--platform linux/arm,linux/arm64,linux/amd64` to build the mutliarch image. Maybe you want to join forces on this topic, as https://github.com/graphite-project/docker-graphite-statsd/issues/128 is also on its way to get multiarch builds on docker hub.

**Comment by jjethwa** [comment]
Sounds good!  Thanks @christian-weiss 

Would probably need to use something like CircleCI, Travis, etc since Open Source projects can build for free and have it build there

**Comment by daniela-waranie** [comment]
@jjethwa you may want to leave a comment in the other ticket to get emails when there is a new comment (like mine from today).

**Comment by jjethwa** [comment]
Thanks @daniela-waranie, I thought I had hit the subscribe button, but must have missed it.  Got it this time 😄

**Comment by ulfklose** [comment]
I'm using https://hub.docker.com/r/cbrosius/icinga2 as an alternative for now but having the official image as a multi arch image would be awesome :-).

**Comment by jjethwa** [comment]
That's a great find, @ulfklose  Thank you so much!

I'll definitely look into his work.  Much appreciated 👍

**Comment by christian-weiss** [comment]
As https://hub.docker.com/r/cbrosius/icinga2 (https://github.com/CBrosius/icinga2/blob/master/Dockerfile.arm32v7) is a fork of jjethwa/icinga2 i hope you can join forces with @CBrosius to make the official repo (his upstream) multi-arch too.

**Comment by Dzordzu** [comment]
I just want to make a ping on this issue. If @jjethwa wouldn't peempt me, I would probably make a pull request in the nearest future that will include ARM Dockerfiles

**Comment by jjethwa** [comment]
Hi @Dzordzu 

That would be really great!  I've been a bit too busy to work on this, so any help would be really appreciated :smiley:

**Comment by CBrosius** [comment]
Hi

For me this was a little project to learn more about docker-hub multiarch-building process and to create an image for my own use. I am really flashed about 50k downloads of my image. Never thought this would be of such huge interest.

If this is of any use for you, feel free to use whatever you want. But I don´t know if I used best practices or something like that. It was more trial and error for me, because my knowledge of docker is still very limited.
My goal was to use the most simple method to integrate multiarch-building in existing Dockerfiles, and to use that directly on Dockerhub because I do not have a dedicated Multiarch-Buildserver at home.

Kindest regards,
Christian...

Btw, today I synced to the latest changes form @jjethwa and activated arm64v8 again. Last time this did not work, but now it looks good. But I have not tested the builds right now.

**Comment by jjethwa** [comment]
Hi @CBrosius 

Really appreciate all of the work you have done on the multiarch builds!  I had taken a look into it at an earlier time when it was just too much work to get docker hub to support it but it looks like your method works really well.  I don't have an arm test environment set up, but I'll see if I can get something set up the next break I have.

I'd love to sync your fork up with this one and then see if we can get it moved over to the official Icinga repo.  Do you have time to work on it together?  I'll send you an invite now.  No pressure!  I just want you to get full credit for getting this major feature working.

**Comment by CBrosius** [comment]
Hi @jjethwa ,
I have never done a PR against another repository. I think I prepared the necessary changes, but I am not sure how to commit them as a correct PR.
Should I just commit my changes and an PR is created automatically?
Kindest regards,
Christian...

**Comment by daniela-waranie** [comment]
There is now an official Github Action powered officially by Docker:
https://github.com/docker/build-push-action
The sad thing is, this Github Action do not support buildx at the moment. 

But the good news is docker is working on buildx support for the official Github Action: 
https://github.com/docker/roadmap/issues/122
as you can see in the docker roadmap: 
https://github.com/docker/roadmap/projects/1
in the "We're Writing The Code"-column.

So you may want to leave a thumbs-up, become an alpha-tester or contribute your findings/code.

**Comment by jjethwa** [comment]
Hi @CBrosius 
Sorry for the delayed response again.  Yes, you would commit your changes in your repo (I think you've already done that), then you would go to: https://github.com/jjethwa/icinga2/compare/master...CBrosius:master
