### ISSUE TITLE
Cannot send emails with mail command

### ISSUE THREAD

**Issue by SemaiCZE** [jjethwa/icinga2#221]
Hi,

I have icinga deployment in my home kubernetes cluster. My `msmtp` is correctly configured and I can send emails this way from inside the pod:
```
# echo "test 123" | msmtp "ptr.stef@gmail.com"
Feb 23 21:05:53 host=smtp.seznam.cz tls=on auth=on user=icinga@ps.stdin.cz from=icinga@ps.stdin.cz recipients=ptr.stef@gmail.com mailsize=72 smtpstatus=250 smtpmsg='250 2.0.0 Mail 3226448675 queued for delivery in session 5a8500000003.' exitcode=EX_OK
```

But when I try to use `mail` command from `mailutils` package, I get an error:
```
# echo "test 123" | mail -s "Subject" "ptr.stef@gmail.com"
mail: cannot send message: Process exited with a non-zero status
```

From my debugging session I found that `mail` is pointing to binary from `mailutils` package and `sendmail` is alias to `msmtp`:
```
/usr/bin/mail -> /etc/alternatives/mail -> /usr/bin/mail.mailutils
/usr/sbin/sendmail -> /usr/bin/msmtp
```

Sending message via command line fails with
```
# echo "test 123" | /usr/bin/mail.mailutils --debug-level=10 -s "Subject" "ptr.stef@gmail.com"
mail.mailutils: sendmail binary: /usr/sbin/sendmail
mail.mailutils: Trying system...
mail.mailutils: system yields 0=Success
mail.mailutils: source=system, name=root, passwd=x, uid=0, gid=0, gecos=root, dir=/root, shell=/bin/bash, mailbox=/var/mail/root, quota=0, change_uid=1
mail.mailutils: Trying system...
mail.mailutils: system yields 0=Success
mail.mailutils: source=system, name=root, passwd=x, uid=0, gid=0, gecos=root, dir=/root, shell=/bin/bash, mailbox=/var/mail/root, quota=0, change_uid=1
mail.mailutils: mu_mailer_send_message(): using From: root@icinga2-58df585c6b-k6jl8
mail.mailutils: Sending headers...
mail.mailutils: Sending body...
mail.mailutils: /usr/sbin/sendmail exited with: 65
mail.mailutils: cannot send message: Process exited with a non-zero status
mail.mailutils: Trying system...
mail.mailutils: system yields 0=Success
mail.mailutils: source=system, name=root, passwd=x, uid=0, gid=0, gecos=root, dir=/root, shell=/bin/bash, mailbox=/var/mail/root, quota=0, change_uid=1
```

I guess it's because `mailutils` are trying to put wrong from address to sendmail (msmtp). If I install `bsd-mailx` package, `mail` command is alias to `/usr/bin/bsd-mailx` a now everything works. Can you please use `bsd-mailx` package instead of `mailutils`?

Thank you very much,
-Petr

**Comment by jjethwa** [comment]
Hi @SemaiCZE 

Thanks so much for the detailed analysis.  Just to confirm, you installed bsd-mailx on top of the base icinga2 image or did you remove mailutils first?  I just want to make sure I can repeat the test procedure properly.

**Comment by SemaiCZE** [comment]
Yes, at first I installed `bsd-mailx` on top of the icinga2 image and then everything started to work. Now I can confirm that uninstalling `mailutils` first and installing `bsd-mailx` after that works too, so you should be able just to replace `mailutils` to `bsd-mailx` package in the Dockerfile. I haven't tried the `mail.rc` stuff yet.

**Comment by jjethwa** [comment]
Perfect!  Thanks for confirming both methods @SemaiCZE 

@svenakela My preliminary tests on local worked, but would you be able to do a quick test on your end?   I think the suggestion to replace mailutils with bsd-mailx should be pretty transparent for most.

**Comment by swtrustly** [comment]
@jjethwa I can test this during or after the weekend, so will be a few days away. But will for sure test it!

**Comment by SemaiCZE** [comment]
@swtrustly any update on this?

**Comment by Dzordzu** [comment]
Just want to make a reminder

**Comment by jjethwa** [comment]
Sorry @Dzordzu and @SemaiCZE 

I totally forgot about this after my initial testing.  I'll never the PR now

**Comment by swtrustly** [comment]
Me too! I totally forgot about it...
@jjethwa you'll fix it right away or do you want a PR?

**Comment by Dzordzu** [comment]
@jjethwa Thanks a lot!
@swtrustly PR with it is already merged
