### ISSUE TITLE
Question : Rerey_interval unknown state

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#23]
Hello,

I have a small question (I am still using an old version of your icinga container).

I configured a template like this : 

```bash
template Service "my_service" {
	import "generic-service"
	check_interval = 5m
	retry_interval = 30s
}
```

The check_interval (5 minutes) is working. 

When a host has a critical state, the next check (retry_interval) is working (30 seconds).

But my problem is if I have an unknown state(purple color), the next check is in 5 minutes and not 30 seconds.

Do you know why and how to fix it ?

Thank you

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Is the check returning the UNKNOWN status because there is a problem?  Some checks have a flag that allows the UNKNOWN states to be changed to CRITICAL.  If not, you might want to change that in the script itself.

**Comment by Quentinvarquet** [comment]
Thank you for your answer!

I have an unknown state because I am doing all my check_snmp from an other
server and sometimes the ssh connection has some problems. After the next
check it always works.  That's why I want to do it 30 seconds after the
first check and not 5 minutes.

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Yeah, in that case I would definitely have it go to CRITICAL always instead of UNKNOWN and have a dependency set up for the SSH service on the target server 🙂

**Comment by Quentinvarquet** [comment]
Any idea how to change it for a critical? (always)

**Comment by jjethwa** [comment]
@Quentinvarquet 

Depends on the check script you are using.  Some have flags that will make all UNKNOWN statuses return CRITICAL instead.  Some need to be manually modified to return CRITICAL instead :)

**Comment by Quentinvarquet** [comment]
Perfect thank you!
