### ISSUE TITLE
Running node wizard and excluding conf.d breaks director module

### ISSUE THREAD

**Issue by jangeador** [jjethwa/icinga2#230]
When I create a new instance using docker-compose and then I go to the shell of the icinga2 container and run the node wizard to exclude conf.d because I want to use Director, and that is one of the recommended steps. After the line gets commented and the conf file looks like:

```
// Disabled by the node setup CLI command on 2020-05-11 18:15:21 +0000
// include_recursive "conf.d"
// Added by the node setup CLI command on 2020-05-11 18:15:21 +0000
include "conf.d/api-users.conf"
```
The director no longer works, when I try to deploy the pending changes it tells me:
```
Unable to detect your Icinga 2 Core version (DeployFormsBug7530.php:70)
```

If I edit the file and uncomment the `include_recursive "conf.d"` then everything works again. Which part of the conf.d is missing so that I can just add that part without having everything else that I dont need from conf.d directory?

**Comment by jjethwa** [comment]
Hi @jangeador 

Director should be ready to go when starting the container by default AFAIK.  The setup script for it should take care of it.   See: https://github.com/jjethwa/icinga2/blob/master/content/opt/setup/61-icingaweb2-director

Just make sure that ICINGA2_FEATURE_DIRECTOR is not set to 0/false
