### ISSUE TITLE
Missing "-y" in Dockerfile line 53

### ISSUE THREAD

**Issue by felixhopfauf** [jjethwa/icinga2#234]
Missing "-y" in Dockerfile line 53
Build will fail with error

**Comment by jjethwa** [comment]
Hi @felixhopfauf 

Can you submit a PR?

**Comment by skupjoe** [comment]
Indeed I am hitting this also since a04b340.

PR submitted.

**Comment by jjethwa** [comment]
Thanks @skupjoe 

Just merged it and Docker Hub is building it now 😄

**Comment by jjethwa** [comment]
Interesting, it seems like the NOINTERACTIVE is not being honoured by apt-get
