### ISSUE TITLE
v2.11.4

### ISSUE THREAD

**Issue by skupjoe** [jjethwa/icinga2#236]
A new version of Icinga2 has been released. Please consider building/hosting this in [Docker Hub(https://hub.docker.com/r/jordan/icinga2/).

https://icinga.com/2020/06/18/icinga-2-11-4/

**Comment by jjethwa** [comment]
Hi @skupjoe 

Thanks for the heads up.  Sorry, it's been a bit hectic for the past few months.  This should be available in latest and a tagged release will be available once the base set of tests pass :smile:

**Comment by jjethwa** [comment]
https://hub.docker.com/layers/jordan/icinga2/2.11.4/images/sha256-22aebf7deb491744d8005302ce1ce6df5876fe64fab4a40d7040d8db160c704c?context=repo
