### ISSUE TITLE
Authenticate against github

### ISSUE THREAD

**Issue by gvenka008c** [jjethwa/icinga2#24]
Does icinga2 supports user authentication against github? For Ex, We have all the user's in github. We want icinga2 to authenticate against certain groups in github and allow access to icinga2 dashboard.

**Comment by jjethwa** [comment]
Hi @gvenka008c 

I don't believe IcingaWeb2 does according to the documentation: https://github.com/Icinga/icingaweb2/blob/master/doc/authentication.md

However, it should be pretty easy to develop an authentication module to support that.  I would contact the Icinga development team via the mailing list: https://lists.icinga.org/pipermail/icinga-users/ , Monitoring Portal forum: http://www.monitoring-portal.org/ or IRC: http://webchat.freenode.net/?channels=icinga
