### ISSUE TITLE
MySQL 8 removes shorthand for creating user with permissions

### ISSUE THREAD

**Issue by skupjoe** [jjethwa/icinga2#243]
After switching to MySQL 8, I am seeing this sort of error during `/opt/setup/50-icinga2` which prevents initialization:

```
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY '<PASS>'' at line 4
```

It looks like the shorthand syntax of assigning users + permissions in the same SQL declaration is no longer supported:
https://ma.ttias.be/mysql-8-removes-shorthand-creating-user-permissions/

**Comment by skupjoe** [comment]
https://github.com/jjethwa/icinga2/pull/244

**Comment by jjethwa** [comment]
Thanks for the heads up, @skupjoe   

The PR https://github.com/jjethwa/icinga2/pull/244 was closed by you, can you re-open and let me know when ready?

**Comment by skupjoe** [comment]
PR #245 opened

**Comment by jjethwa** [comment]
Thanks @skupjoe 
Merged and available in latest.  Looks good to me, let me know how it works for you

**Comment by skupjoe** [comment]
Yup working well. MySQL8 on AWS RDS + Icinga 2.12.0

(Also, looks like 2.12.1 was just released)

**Comment by jjethwa** [comment]
Great, thanks, @skupjoe 

I'll tag 2.12.1 and release it as it has your changes already 😄
