### ISSUE TITLE
 ERROR 1045 (28000): Access denied for user 'icinga2'@'172.18.0.2' (using password: YES)

### ISSUE THREAD

**Issue by AqujZ1K9** [jjethwa/icinga2#251]
when ever I'm restarting the icinga container, after a successful build, it fails with:

`ERROR 1045 (28000): Access denied for user 'icinga2'@'172.18.0.2' (using password: YES)`

I'm using the docker-compose file with an extra mysql container on site.
I'm pretty sure I'm missing something here. But what ?

**Comment by jjethwa** [comment]
Hi @AqujZ1K9 

So you're using the docker-compose but with an external MySQL/MariaDB container? If so, you need to set DEFAULT_MYSQL_HOST, MYSQL_ROOT_PASSWORD, and  DEFAULT_MYSQL_PASS in the docker-compose file.

**Comment by AqujZ1K9** [comment]
Sorry I'm a but confused.
The Doc says
`If you use the image plain or the docker-compose.yml project, you don't have to worry about anything for MySQL.`
- which I do.
First initial start all fine it builds up and its all good. I'm having the Issue when restarting the container.

**Comment by AqujZ1K9** [comment]
oh okay, all my fault! 
the Docs also clearly saying:
`DEFAULT_MYSQL_PASS: The password for the MySQL user. (defaults to randomly generated string) - It is recommended that you set this value to ensure container restarts work as expected.`
doing that it works perfectly fine.

Maybe it's a good to add this to the "docker-compose" section, for lazy readers like me :D 
Thank you very much for your help!

**Comment by jjethwa** [comment]
Sounds good, I'll get that done.  Thanks for the suggestion 👍
