### ISSUE TITLE
Restarting problem

### ISSUE THREAD

**Issue by vbence98** [jjethwa/icinga2#254]
Hi!

I just started learning Icinga and set up on docker. Everything is fine until I would like to restart the container or the host device, then this error message comes up. Where can I change the password for the db server to solve this problem?

Generating locales (this might take a while)...
Clearing symlinks in /etc/ssl/certs...
Generation complete.
done.
Updating certificates in /etc/ssl/certs...
126 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
[....] Starting MariaDB database server: mysqld .[ ok .
Site 000-default already enabled
Site icingaweb2-ssl already disabled
Site icingaweb2-ssl-redirect already disabled
Pinging localhost:3306
mysqld is alive
warning/cli: Feature 'ido-mysql' already enabled.
warning/cli: Feature 'livestatus' already enabled.
warning/cli: Feature 'compatlog' already enabled.
warning/cli: Feature 'command' already enabled.
**,ERROR 1045 (28000): Access denied for user 'icinga2'@'localhost' (using password: YES)
run-parts: /opt/setup/50-icinga2 exited with return code 1**

Regards,
Bence

**Comment by jjethwa** [comment]
Hi @vbence98 

If you're using docker-compose, make sure to set DEFAULT_MYSQL_PASS in the secrets or compose file.  If using the regular command line, set DEFAULT_MYSQL_PASS as an environment variable as part of the docker run command.  Let me know if that works.

**Comment by vbence98** [comment]
Thanks a lot! It solved my problem. :)

**Comment by vbence98** [comment]
Hi @jjethwa!

Thanks, I passed a password to the env value you sent and it stopped failing to restart!

**Comment by jjethwa** [comment]
Great news!
