### ISSUE TITLE
Error standard_init_linux.go:219 in Docker Desktop

### ISSUE THREAD

**Issue by jiri-lenik** [jjethwa/icinga2#256]
Hi - thanks for this container.

I am having troubles in Docker Desktop, i tried WSL2 / Hyper-V, tried to change debian version, but icinga2 container still returns only standard_init_linux.go:219: exec user process caused: no such file or directory.

**Comment by jjethwa** [comment]
Hi @jiri-lenik 

Sorry to hear about the issue.  I don't have a test rig to reproduce that issue. Is there anything more in the logs that might help?  What change did you make?

**Comment by x-sven** [comment]
I can confirm, no further information available. Possibly the source is in one of the underlying stacks. Will try to look deeper in the dockerfile later...

**Comment by jiri-lenik** [comment]
Unfortunately, there are not so much information. I just cloned, add secrets file and run compose up. Other two containers started OK, only icinga2 has this problem.

I am docker newbie, so just tried some hints I found - I tried to switch between WSL/Hyper-V, switch to debian stretch, just for case.

Only output message is "standard_init_linux.go:219: exec user process caused: no such file or directory"

For me it looks like a problem in entrypoint script, but as I said, I am a docker newbie.

**Comment by jjethwa** [comment]
Thanks, @x-sven and @jiri-lenik 

I'm wondering if it might be the chown commands in the entry point script.  I'm not sure how Hyper-V handles volumes and ownership.  The chown commands were added for the cases where users added empty volumes or volumes are moves across systems.

**Comment by jiri-lenik** [comment]
Yes, I can confirm, that the problem is in sharing files between NTFS and linux volumes.

I followed this article, and it works, if you compose the image from debian image in the WSL on windows.

**Comment by jjethwa** [comment]
Thanks for the update @jiri-lenik 

Do you mind linking to the article?

**Comment by jiri-lenik** [comment]
Sorry, did not notice the missing link  - comment updated

**Comment by jjethwa** [comment]
Thanks, you rock 😄
