### ISSUE TITLE
error after restart

### ISSUE THREAD

**Issue by Cptn-Future** [jjethwa/icinga2#259]
mysql       | 2021-03-26  1:37:19 50 [Warning] Access denied for user 'icinga2'@'192.168.112.3' (using password: YES)
icinga2_1   | ERROR 1045 (28000): Access denied for user 'icinga2'@'192.168.112.3' (using password: YES)

**Comment by Cptn-Future** [comment]
error after restart
mysql       | 2021-03-26  1:37:19 50 [Warning] Access denied for user 'icinga2'@'192.168.112.3' (using password: YES)
icinga2_1   | ERROR 1045 (28000): Access denied for user 'icinga2'@'192.168.112.3' (using password: YES)

**Comment by Cptn-Future** [comment]
error after restart
mysql       | 2021-03-26  1:37:19 50 [Warning] Access denied for user 'icinga2'@'192.168.112.3' (using password: YES)
icinga2_1   | ERROR 1045 (28000): Access denied for user 'icinga2'@'192.168.112.3' (using password: YES)

**Comment by jjethwa** [comment]
Hi @Cptn-Future 

Did you set the variables for the database like DEFAULT_MYSQL_PASS?

**Comment by Cptn-Future** [comment]
Hi @Jordan Jethwai
I apologize if this text sounds a bit bumpy. English is not my mother tongue and I don't have a good enough command of it for a conversation, so I use the google translator.
I'm confused, I tested it on a freshly installed Centos8 VM and an Ubuntu 20 LTS VM. As suggested in the readme.
in "secrets_sql.env" "MYSQL_ROOT_PASSWORD = r00tpa55wd".
I will soon despair I have had the problem for more than a week. After the first successful start with "docker-compose up -d", I can log on to the web interface and operate everything, everything runs smoothly. If I then exit with "docker-compose down" and then restart the error.

"mysql | 2021-03-26 9:40:40 20 [Warning] Access denied for user 'icinga2'@'192.168.176.2' (using password: YES)
icinga2_1 | ERROR 1045 (28000): Access denied for user 'icinga2'@'192.168.176.2' (using password: YES)
icinga2_1 | run-parts: / opt / setup / 50-icinga2 exited with return code 1
icinga2_icinga2_1 exited with code 1 "

I came to reproduce this behavior several times, I deleted the whole folder and created everything with "git clone https://github.com/jjethwa/icinga2.git" then created the file "secrets_sql.env" and stored the variable "and received it always the same result. 1x start then nothing works anymore.

best regards
tommy
***@***.***

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Freitag, März 26, 2021 7:57 AM schrieb Jordan Jethwa ***@***.***>:

**Comment by Cptn-Future** [comment]
### Dieses Problem konnte gelöst werden, Danke für den Hinweis. /  This problem could be solved, thanks for the hint.
thy @jjethwa 

file ==> **secrets_sql.env** _has now with 2 lines with passwords_ 
--------------------------------------------------------------------------------
MYSQL_ROOT_PASSWORD=extremGOODPa$$W0RD
DEFAULT_MYSQL_PASS=theBe$tPa$$ofTheUnivers3
--------------------------------------------------------------------------------

**Comment by jjethwa** [comment]
That's great news, @Cptn-Future 

Have a great weekend 😄
