### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by gvenka008c** [jjethwa/icinga2#26]
Hi Jordan,

I have installed the dockerized version of icinga2 using your repo. Can you give a simple example of adding one of remote host to the webUI and showing the alerts? I am basically looking for the config files that we need to add to have the alerts shown in UI.

Thanks,
Govind

**Comment by gvenka008c** [comment]
@jjethwa I have figured it out. But when i try to run the below within the docker container, i am getting the error as below

./check_nrpe -H xx.xxx.xxx.xxx -c check_ssh_6.6
CHECK_NRPE: Socket timeout after 10 seconds.

How can i ensure all the clients can reach this dockerrized icinga? thoughts?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

That's great news!  Sorry, it's been a really busy few days :) 

I don't recommend using nrpe personally due to security concerns, but if you are using it, is the nrpe agent installed on the target host?

**Comment by gvenka008c** [comment]
@jjethwa Yes

# ps -ef | grep nrpe

root     16746  3407  0 21:22 pts/2    00:00:00 grep --color=auto nrpe
nrpe     27951     1  0 Apr04 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d -n

**Comment by jjethwa** [comment]
Hi @gvenka008c 

What is strange about this is you're getting 
```CHECK_NRPE: Socket timeout after 10 seconds.```

That leads me to think there may be some network issue?  Maybe the request is being blocked by a firewall?  The container does not need any special set up since it is the one initiating the connection to the target server.

I'm assuming that the nrpe.cfg on the target server has the IP address of the container's host in the allowed_hosts= section too, right?  What happens when you just run a regular check_nrpe?

```./check_nrpe -H xx.xxx.xxx.xxx```

Thanks :)

**Comment by gvenka008c** [comment]
@jjethwa 

[root@10bdc30b4400 plugins]# ./check_nrpe -H xx.xxx.xxx.xxx -n
NRPE v2.15

I checked the nrpe.cfg file on target server and allowed_host has the IP address of the machine where icinga is running as a docker.

**Comment by jjethwa** [comment]
Hi @gvenka008c 

It looks like nrpe connectivity is confirmed since you received the NRPE version in the response:
```
[plugins]# ./check_nrpe -H xx.xxx.xxx.xxx -n
NRPE v2.15
```

The nrpe command you are trying to execute on the target server: check_ssh_6.6

What is that doing?

**Comment by gvenka008c** [comment]
@jjethwa It just check for the Open SSH version on the remote machine.

command[check_ssh_6.6]=/usr/lib64/nagios/plugins/check_ssh -r "OpenSSH_6.6.1" -p 22 -H localhost

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Well this is not the solution to that problem, but you can use check_ssh from the container itself to check if SSH is working OK on the target server, right?  No need to use nrpe for that unless there are firewall rules blocking SSH from the container for example.  Just throwing out an idea :)

**Comment by gvenka008c** [comment]
@jjethwa The above was just an example one. We use a lot of nrpe based checkings on the remote machine. We already have Icinga environment running for the past 2 years. We are trying to explore dockerized version to see how it works.

**Comment by jjethwa** [comment]
@gvenka008c 

Got it! :)  I ran some tests locally with a brand new icinga2 container on one host and a a host with the nrpe agent set up (with the icinga2 container's host in the allowed list) and was able to get the check_nrpe command to work successfully.

In your case, check_nrpe (container) seems to be able to connect to the nrpe agent (target).  This was proven by getting the nrpe agent version back.  I'm not sure why check_nrpe is failing when you try to issue the check_ssh_6.6 command though.  Is there anything on the container's host or target that could be blocking it?  The container does not require anything special for outbound connections.

**Comment by gvenka008c** [comment]
@jjethwa I checked the firewall rules and all the ports that are mentioned is opened. 

[root@10bdc30b4400 /]# /usr/lib64/nagios/plugins/check_nrpe -H xx.xxx.xxx.xxx -n
NRPE v2.15

[root@10bdc30b4400 /]# /usr/lib64/nagios/plugins/check_nrpe -H xx.xxx.xxx.xxx -c check_ssh_6.6
CHECK_NRPE: Socket timeout after 10 seconds.

I feel for some reason docker is not able to communicate outside the system. I see the docker is binded to local host as [0.0.0.0:3080->80/tcp]. Should this be mapped to IP address of the machine? Thoughts.

22/tcp, 443/tcp, 3306/tcp, 5665/tcp, 0.0.0.0:3080->80/tcp

**Comment by jjethwa** [comment]
Hi @gvenka008c 

It could be something with the way your host's docker daemon is set up for the networking: https://docs.docker.com/engine/userguide/networking/dockernetworks/

I use CoreOS as my host and docker is bound to localhost like yours shows:

```
624739f4425d        jordan/icinga2:latest        "/opt/run"               7 days ago          Up 7 days           443/tcp, 0.0.0.0:80->80/tcp, 5665/tcp   icinga2
```

**Comment by gvenka008c** [comment]
@jjethwa I found the issue. I made it to talk without using SSL and was able to get the output. 

How did you start the nrpe within the container? For some reason i don't see nrpe running on the container for me. Here is the supervisord.conf i added. 

[program:nrpe]
command=/usr/sbin/nrpe -d -n
redirect_stderr=true

**Comment by jjethwa** [comment]
Hi @gvenka008c 

The nrpe agent is not installed by default.  You will need to install it

```
apt-get install nagios-nrpe-server
```

**Comment by gvenka008c** [comment]
@jjethwa I have installed the nrpe inside the docker and all the nagios related plugins.

[root@e6549b24a036 etc]# rpm -qa | grep nrpe
nrpe-2.15-7.el7.x86_64
nagios-plugins-nrpe-2.15-7.el7.x86_64

I am not sure if this is the right way to start nrpe within supervisord

[program:nrpe]
command=/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d -n
redirect_stderr=true

Thoughts?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

For supervisord, you can't run the agent in daemon mode.  supervisord needs it to be run as a foreground application so it can monitor it's status.  Try doing that and reloading the supervisord config and you should be good :)

**Comment by gvenka008c** [comment]
@jjethwa For some reason nrpe is getting killed

[root@e6549b24a036 etc]# supervisorctl
httpd                            RUNNING   pid 37, uptime 0:03:24
icinga2                          RUNNING   pid 40, uptime 0:03:24
mariadb                          RUNNING   pid 39, uptime 0:03:24
nrpe                             FATAL     Exited too quickly (process log may have details)
sshd                             RUNNING   pid 38, uptime 0:03:24

2016-04-08 19:00:29,248 DEBG fd 20 closed, stopped monitoring <POutputDispatcher at 39624360 for <Subprocess at 39086920 with name nrpe in state STARTING> (stdout)>
2016-04-08 19:00:29,248 INFO exited: nrpe (exit status 3; not expected)
2016-04-08 19:00:30,250 INFO gave up: nrpe entered FATAL state, too many start retries too quickly

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Unfortunately I don't know enough about nrpe to know what's going on.  If nrpe is able to run in foreground mode (not as a daemon) then that should be it.  You may have to create a wrapper script like I did for mysql: https://github.com/jjethwa/icinga2/blob/master/content/opt/supervisor/mysql_supervisor

One thing, I notice you're doing a lot of customizing to the container.  You may want to fork this repo, add your customizations in, etc so you can easily start up another container with your defaults.

Also, I don't think you need to have SSH running in the container.  You can use docker exec or nsenter access it from the host :)

**Comment by gvenka008c** [comment]
@jjethwa I have to make changes to one of the conf file to set it to true as below. That fixed the issue and all my alerts re up :) Thanks a lot for your help. 

----/usr/share/icinga2/include/command-plugins.conf*
vars.nrpe_no_ssl = true

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Great news!  Thanks so much and have fun :)
