### ISSUE TITLE
Restart Container Can not connect do Database

### ISSUE THREAD

**Issue by mochoandre** [jjethwa/icinga2#261]
Hello and regards,
I've installed your docker container in Ubuntu 20.04 and installation goes smothly. 

After installation, container is running, I can access web Incinga2Web and all seems ok.
As soon as I restart th container, It will not start again and I can not start it. It looks like it looses conection to DB. What Can I do?

> 
> [2021-04-16 14:14:34 +0000] information/HttpServerConnection: Request: GET /v1/objects/checkcommands (from [172.17.0.6]:59466), user: icinga2-director, agent: , status: OK).
> 
> [2021-04-16 14:14:34 +0000] information/HttpServerConnection: Request: POST /v1/console/execute-script (from [172.17.0.6]:59466), user: icinga2-director, agent: , status: OK).
> 
> [2021-04-16 14:14:34 +0000] information/HttpServerConnection: Request: GET /v1/objects/notificationcommands (from [172.17.0.6]:59466), user: icinga2-director, agent: , status: OK).
> 
> [2021-04-16 14:14:34 +0000] information/HttpServerConnection: Request: POST /v1/console/execute-script (from [172.17.0.6]:59466), user: icinga2-director, agent: , status: OK).
> 
> [2021-04-16 14:14:34 +0000] information/HttpServerConnection: Request: GET /v1/objects/eventcommands (from [172.17.0.6]:59466), user: icinga2-director, agent: , status: OK).
> 
> [2021-04-16 14:14:37 +0000] information/HttpServerConnection: HTTP client disconnected (from [172.17.0.6]:59466)
> 
> [2021-04-16 14:14:40 +0000] information/WorkQueue: #5 (GraphiteWriter, graphite) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
> 
> [2021-04-16 14:14:40 +0000] information/WorkQueue: #7 (ApiListener, RelayQueue) items: 0, rate: 0.2/s (12/min 12/5min 12/15min);
> 
> [2021-04-16 14:14:40 +0000] information/WorkQueue: #8 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> 
> [2021-04-16 14:14:40 +0000] information/IdoMysqlConnection: Pending queries: 0 (Input: 3/s; Output: 94/s)
> 
> [2021-04-16 14:15:30 +0000] information/ConfigObjectUtility: Created and activated object '3fd89c5dd580!load!b1b73864-8943-42ff-a575-adc7767280e8' of type 'Downtime'.
> 
> [2021-04-16 14:15:30 +0000] information/Downtime: Added downtime '3fd89c5dd580!load!b1b73864-8943-42ff-a575-adc7767280e8' between '2021-04-17 02:00:00' and '2021-04-17 03:00:00', author: 'icingaadmin', fixed
> 
> [2021-04-16 14:16:06 +0000] information/Checkable: Checkable '3fd89c5dd580!disk /' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
> 
> [2021-04-16 14:16:06 +0000] information/Notification: Sending 'Problem' notification '3fd89c5dd580!disk /!mail-icingaadmin' for user 'icingaadmin'
> 
> [2021-04-16 14:16:06 +0000] information/Notification: Completed sending 'Problem' notification '3fd89c5dd580!disk /!mail-icingaadmin' for checkable '3fd89c5dd580!disk /' and user 'icingaadmin' using command 'mail-service-notification'.
> 
> [2021-04-16 14:16:06 +0000] warning/PluginNotificationTask: Notification command for object '3fd89c5dd580!disk /' (PID: 2615, arguments: '/etc/icinga2/scripts/mail-service-notification.sh' '-4' '127.0.0.1' '-6' '::1' '-b' '' '-c' '' '-d' '2021-04-16 14:16:06 +0000' '-e' 'disk /' '-l' '3fd89c5dd580' '-n' '3fd89c5dd580' '-o' 'DISK UNKNOWN - free space:' '-r' 'root@localhost' '-s' 'UNKNOWN' '-t' 'PROBLEM' '-u' 'disk /' '-v' 'false') terminated with exit code 36, output: mail: cannot send message: Process exited with a non-zero status
> 
> 
> [2021-04-16 14:16:28 +0000] information/Checkable: Checkable '3fd89c5dd580!ping6' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
> 
> [2021-04-16 14:16:28 +0000] information/Notification: Sending 'Problem' notification '3fd89c5dd580!ping6!mail-icingaadmin' for user 'icingaadmin'
> 
> [2021-04-16 14:16:28 +0000] information/Notification: Completed sending 'Problem' notification '3fd89c5dd580!ping6!mail-icingaadmin' for checkable '3fd89c5dd580!ping6' and user 'icingaadmin' using command 'mail-service-notification'.
> 
> [2021-04-16 14:16:28 +0000] warning/PluginNotificationTask: Notification command for object '3fd89c5dd580!ping6' (PID: 2670, arguments: '/etc/icinga2/scripts/mail-service-notification.sh' '-4' '127.0.0.1' '-6' '::1' '-b' '' '-c' '' '-d' '2021-04-16 14:16:28 +0000' '-e' 'ping6' '-l' '3fd89c5dd580' '-n' '3fd89c5dd580' '-o' '/bin/ping -6 -n -U -w 10 -c 5 ::1
> 
> CRITICAL - Could not interpret output from ping command' '-r' 'root@localhost' '-s' 'UNKNOWN' '-t' 'PROBLEM' '-u' 'ping6' '-v' 'false') terminated with exit code 36, output: mail: cannot send message: Process exited with a non-zero status
> 
> 
> [2021-04-16 14:19:30 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
> 
> [2021-04-16 14:19:50 +0000] information/WorkQueue: #5 (GraphiteWriter, graphite) items: 0, rate: 0.283333/s (17/min 93/5min 99/15min);
> 
> [2021-04-16 14:19:50 +0000] information/WorkQueue: #8 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> 
> [2021-04-16 14:19:50 +0000] information/WorkQueue: #7 (ApiListener, RelayQueue) items: 0, rate: 0.8/s (48/min 265/5min 289/15min);
> 
> [2021-04-16 14:19:50 +0000] information/IdoMysqlConnection: Pending queries: 9 (Input: 3/s; Output: 3/s)
> 
> [2021-04-16 14:24:30 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
> 
> [2021-04-16 14:24:59 +0000] information/WorkQueue: #5 (GraphiteWriter, graphite) items: 0, rate: 0.316667/s (19/min 92/5min 194/15min);
> 
> [2021-04-16 14:25:00 +0000] information/WorkQueue: #7 (ApiListener, RelayQueue) items: 0, rate: 0.8/s (48/min 248/5min 545/15min);
> 
> [2021-04-16 14:25:00 +0000] information/WorkQueue: #8 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> 
> [2021-04-16 14:25:00 +0000] information/IdoMysqlConnection: Pending queries: 10 (Input: 4/s; Output: 3/s)
> 
> [2021-04-16 14:26:50 +0000] information/IdoMysqlConnection: Pending queries: 10 (Input: 3/s; Output: 2/s)
> 
> [2021-04-16 14:29:20 +0000] information/IdoMysqlConnection: Pending queries: 10 (Input: 3/s; Output: 2/s)
> 
> [2021-04-16 14:29:30 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
> 
> [2021-04-16 14:30:09 +0000] information/WorkQueue: #5 (GraphiteWriter, graphite) items: 0, rate: 0.3/s (18/min 91/5min 277/15min);
> 
> [2021-04-16 14:30:10 +0000] information/WorkQueue: #8 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> 
> [2021-04-16 14:30:10 +0000] information/WorkQueue: #7 (ApiListener, RelayQueue) items: 0, rate: 0.8/s (48/min 244/5min 753/15min);
> 
> [2021-04-16 14:30:10 +0000] information/IdoMysqlConnection: Pending queries: 9 (Input: 3/s; Output: 2/s)
> 
> [2021-04-16 14:32:40 +0000] information/IdoMysqlConnection: Pending queries: 10 (Input: 3/s; Output: 2/s)
> 
> [2021-04-16 14:33:20 +0000] information/IdoMysqlConnection: Pending queries: 10 (Input: 3/s; Output: 2/s)
> 
> [2021-04-16 14:34:30 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
> 
> [2021-04-16 14:35:19 +0000] information/WorkQueue: #5 (GraphiteWriter, graphite) items: 0, rate: 0.3/s (18/min 91/5min 272/15min);
> 
> [2021-04-16 14:35:20 +0000] information/WorkQueue: #8 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> 
> [2021-04-16 14:35:20 +0000] information/WorkQueue: #7 (ApiListener, RelayQueue) items: 0, rate: 0.8/s (48/min 244/5min 728/15min);
> 
> [2021-04-16 14:35:20 +0000] information/IdoMysqlConnection: Pending queries: 9 (Input: 3/s; Output: 2/s)
> 
> [2021-04-16 14:39:30 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
> 
> 2021-04-16 14:40:20,208 INFO waiting for director, apache2, mysql, icinga2, fatalservice to die
> 
> Shut down
> 
> 2021-04-16 14:40:23,213 INFO waiting for director, apache2, mysql, icinga2, fatalservice to die
> 
> Stopping icinga2 monitoring daemon: icinga2[2021-04-16 14:40:24 +0000] information/Application: Received request to shut down.
> 
> [2021-04-16 14:40:24 +0000] information/Application: Shutting down...
> 
> [2021-04-16 14:40:24 +0000] information/CheckerComponent: 'checker' stopped.
> 
> [2021-04-16 14:40:24 +0000] information/NotificationComponent: 'notification' stopped.
> 
> [2021-04-16 14:40:24 +0000] information/ExternalCommandListener: 'command' stopped.
> 
> [2021-04-16 14:40:24 +0000] information/CompatLogger: 'compatlog' stopped.
> 
> [2021-04-16 14:40:24 +0000] information/GraphiteWriter: 'graphite' paused.
> 
> [2021-04-16 14:40:24 +0000] information/LivestatusListener: 'livestatus' stopped.
> 
> [2021-04-16 14:40:25 +0000] critical/Socket: accept() failed with error code 9, "Bad file descriptor"
> 
> [2021-04-16 14:40:25 +0000] critical/LivestatusListener: Cannot accept new connection.
> 
> [2021-04-16 14:40:25 +0000] information/DbConnection: Pausing IDO connection: ido-mysql
> 
> [2021-04-16 14:40:25 +0000] information/IdoMysqlConnection: Disconnected from 'ido-mysql' database 'icinga2idomysql'.
> 
> [2021-04-16 14:40:25 +0000] information/IdoMysqlConnection: 'ido-mysql' paused.
> 
> [2021-04-16 14:40:25 +0000] information/DbConnection: 'ido-mysql' stopped.
> 
> [2021-04-16 14:40:25 +0000] information/ApiListener: 'api' stopped.
> 
> [2021-04-16 14:40:25 +0000] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
> 
> [2021-04-16 14:40:25 +0000] information/IcingaApplication: Icinga has shut down.
> 
> icinga2 ended graceful.
> 
> .
> 
> 2021-04-16 14:40:25,825 INFO stopped: icinga2 (exit status 0)
> 
> Stopping MariaDB database server: mysqld2021-04-16 14:40:26,372 INFO waiting for director, apache2, mysql, fatalservice to die
> 
> .
> 
> 2021-04-16 14:40:28,443 INFO stopped: mysql (exit status 0)
> 
> Error while sending QUERY packet. PID=2446
> 
> Failed to update daemon info (setting ts_stopped): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away, query was: UPDATE director_daemon_info SET ts_stopped = ? WHERE (instance_uuid_hex = '7e471e689ca949978a85b5c3e00b6f81')
> 
> Zend_Db_Adapter_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php:145 with message: SQLSTATE[HY000] [2002] No such file or directory <- PDOException in /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php:124 with message: SQLSTATE[HY000] [2002] No such file or directory
> 
> 2021-04-16 14:40:29,861 INFO waiting for director, apache2, fatalservice to die
> 
> Generating locales (this might take a while)...
> 
> Generation complete.
> 
> Clearing symlinks in /etc/ssl/certs...
> 
> done.
> 
> Updating certificates in /etc/ssl/certs...
> 
> 137 added, 0 removed; done.
> 
> Running hooks in /etc/ca-certificates/update.d...
> 
> done.
> 
> [....] Starting MariaDB database server: mysqld[ ok .
> 
> Pinging localhost:3306
> 
> mysqld is alive
> 
> Site 000-default already enabled
> 
> Site icingaweb2-ssl already disabled
> 
> Site icingaweb2-ssl-redirect already disabled
> 
> Pinging localhost:3306
> 
> mysqld is alive
> 
> warning/cli: Feature 'ido-mysql' already enabled.
> 
> warning/cli: Feature 'livestatus' already enabled.
> 
> warning/cli: Feature 'compatlog' already enabled.
> 
> warning/cli: Feature 'command' already enabled.
> 
> ERROR 1045 (28000): Access denied for user 'icinga2'@'localhost' (using password: YES)
> 
> run-parts: /opt/setup/50-icinga2 exited with return code 1
>

**Comment by jjethwa** [comment]
Hey @mochoandre 

To ensure restarts, you should set:

DEFAULT_MYSQL_PASS - The database password for the icinga2 user

MYSQL_ROOT_PASSWORD - This is the root (admin) password for the database. The container will try to reset the password for the icinga2 database user if this is available

**Comment by mochoandre** [comment]
Thank you, it looks it now it's surviving restarts. 
I have read the documentation but it for me it was not clear that step. 
Thank you again
