### ISSUE TITLE
mysql root password is mandatory

### ISSUE THREAD

**Issue by ben-64** [jjethwa/icinga2#265]
If we are using an external mysql server and the environment variable `MYSQL_ROOT_PASSWORD` is not defined, there is a bug on the `/opt/helper` script:

```bash
icinga2    | /opt/helpers: line 60: MYSQL_ROOT_PASSWORD: unbound variable
icinga2    | run-parts: /opt/setup/50-icinga2 exited with return code 1
```

This variable should not be mandatory, because we may have already created everything that is needed in term of database/table.

**Comment by jjethwa** [comment]
Hi @ben-64 

Sorry about the issue.  I think we'll probably need a new variable so it can skip the database setup as you suggested.  Do you want to do the legwork on it and submit a PR?

**Comment by markverg** [comment]
> Hi @ben-64
> 
> Sorry about the issue. I think we'll probably need a new variable so it can skip the database setup as you suggested. Do you want to do the legwork on it and submit a PR?

Hi @jjethwa I experienced this issue myself as well, don't want to have my MySQL server root password laying around.
I created my first public PR, so please be kind. Keep up the good work!

Mark

**Comment by jjethwa** [comment]
Hi @markverg

Thanks so much for the PR!  I'll be able to review and test later today.  Really appreciate it! 😃

**Comment by jjethwa** [comment]
Hi @markverg and @ben-64 

Pushed the latest image (just latest as there is no new Icinga2 release yet).  Basic validation looks great.  

Thanks so much, @markverg !!! 🥳
