### ISSUE TITLE
Icinga Director: Salt Ticket Error

### ISSUE THREAD

**Issue by bbkz** [jjethwa/icinga2#268]
When i go to the following page in the director i get a error, maybe the error mentioned in the icinga community link is related and a update of the icinga director to 1.8.1 helps?

* https://community.icinga.com/t/requesting-salt-but-got-none-error/7817

Icinga Director -> Hosts -> [HOSTNAME] -> Agent Tab

```
#0 /usr/local/share/icingaweb2/modules/director/library/Director/IcingaConfig/AgentWizard.php(109): Icinga\Module\Director\IcingaConfig\AgentWizard->getTicketSalt()
#1 /usr/local/share/icingaweb2/modules/director/library/Director/IcingaConfig/AgentWizard.php(141): Icinga\Module\Director\IcingaConfig\AgentWizard->getTicket()
#2 /usr/local/share/icingaweb2/modules/director/library/Director/Web/SelfService.php(256): Icinga\Module\Director\IcingaConfig\AgentWizard->renderWindowsInstaller()
#3 /usr/local/share/icingaweb2/modules/director/library/Director/Web/SelfService.php(52): Icinga\Module\Director\Web\SelfService->showLegacyAgentInstructions(Object(Icinga\Module\Director\Controllers\HostController))
#4 /usr/local/share/icingaweb2/modules/director/application/controllers/HostController.php(502): Icinga\Module\Director\Web\SelfService->renderTo(Object(Icinga\Module\Director\Controllers\HostController))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->agentAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

**Comment by jjethwa** [comment]
Hi @bbkz 

I'm sorry to hear about the issue and thanks for providing the details.  I haven't been able to build a newer version of the container on Hub due to some changes on their end.  I'm working with them to sort that out, but it's been a few months already.  Have you tried cloning the repo and building the image locally?  I know it's not the greatest option.

**Comment by bbkz** [comment]
Hi @jjethwa 

Thank you for the information. Yes i cloned the repo and changed from 1.8.0 -> 1.8.1, as far as i see it seems to solve the issue.

**Comment by jjethwa** [comment]
Thanks for the update, @bbkz 👍 

I'll go ahead and make the change to the repo and hopefully Docker Hub will be able to resolve the build issues so there's a new working image sometime

**Comment by jjethwa** [comment]
Hey @bbkz 

I was able to push the latest and 2.13.1 tagged versions for x86_64, ARM builds still have the issue.

**Comment by bbkz** [comment]
Hoi @jjethwa 

Thank you! I just tried it and it works on x86_64.
