### ISSUE TITLE
pull from github

### ISSUE THREAD

**Issue by gvenka008c** [jjethwa/icinga2#27]
@jjethwa Is there a way i can pull all my icinga monitor config files from github within docker using my NT account? Also one we pull the config files, is there a way we can do the below within docker? Also is there a way to push the config file changes using Ansible playbook?

```
#service icinga2 reload
#service nrpe reload
```

Thoughts? Thanks.

Thanks,
Govind

**Comment by gvenka008c** [comment]
@jjethwa I was able to pull from git repo. Closing it. Thanks.

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Sorry for the late response.  Sounds like you have it working thoug :)  The easiest way is to use a volume for /etc/icinga2 (also the database would be good for persistence) then pull the configs down on the container host.  Then use docker exec to reload the config

```
sudo docker exec icinga2 service icinga2 reload
```

**Comment by gvenka008c** [comment]
@jjethwa Thanks. We wanted to keep all our config in github. So we can clone the repo inside the container.

After i cloned the repo, I am seeing the as below
Service Status: UNKNOWN
CHECK_​NRPE: Error receiving data from daemon.

I was able to run the below command inside docker and get the desired output.

```
check_nrpe -H hostname -c command -n
```

Not sure why Icinga Web is throwing error. Also under System > Monitoring Health it is showing as Backend icinga2 is not running. Any thoughts?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Check the logs under /var/log/icinga2  That should tell you why Icinga2 failed to start.  Maybe a bad configuration?

**Comment by gvenka008c** [comment]
@jjethwa I didn't see any issues in the log

```
#/var/log/icinga2/icinga2.log
[2016-04-12 14:14:06 +0000] information/ConfigCompiler: Compiling config file: /var/lib/icinga2/modified-attributes.conf
[2016-04-12 14:14:06 +0000] information/IdoMysqlConnection: MySQL IDO instance id: 1 (schema version: '1.14.0')
[2016-04-12 14:14:07 +0000] information/IdoMysqlConnection: Finished reconnecting to MySQL IDO database in 0.669704 second(s).

```

**Comment by gvenka008c** [comment]
@jjethwa I killed the running container and started a new one. And now all the alerts are back up and running without issues..

How can i get rid of the alerts that is showing on web for docker-icinga2?

**Comment by jjethwa** [comment]
Hi @gvenka008c 

If you're using Icinga Web 2 that is on the same container as Icinga2 then the alerts should automatically clear.  Are you using a separate container for Icinga2 and Icinga Web 2 (or Icinga Classic UI)?

**Comment by gvenka008c** [comment]
@jjethwa No. I am using a single container for both icinga2 and icinga web2.

**Comment by jjethwa** [comment]
Hi @gvenka008c 

That's strange.  Just to confirm, after starting a new container to load up config changes, you are still seeing alerts in Icinga Web 2 (or Classic UI) for checks that have passed in Icinga2 (as confirmed in the icinga2.log) ?

**Comment by gvenka008c** [comment]
<img width="626" alt="screen shot 2016-04-12 at 5 08 00 pm" src="https://cloud.githubusercontent.com/assets/13439779/14475675/2bda8c54-00d1-11e6-9873-64a19f268af3.png">

**Comment by jjethwa** [comment]
@gvenka008c 

Thanks, the screenshot helped.  The swap check will always fail since it's a container.  I left that check in there by default so new users could see that checks were working properly (SSH and Swap tests should be critical and the rest should be OK).  Not sure what the random checks are, but I assume those statuses are OK? :)

**Comment by gvenka008c** [comment]
@jjethwa Thanks. Is there a way i can restart nrpe and icinga within container? For Ex: I wanted to pull the monitors from my git repo and when we add new alerts we need to reload icinga. Also if for any reason if we need to restart any services, only way is to restart the container? Thoughts.

**Comment by jjethwa** [comment]
Hi @gvenka008c 

Use docker exec:
```
sudo docker exec icinga2 service icinga2 reload
```

**Comment by gvenka008c** [comment]
@jjethwa 

```
$ sudo docker exec icinga2 service icinga2 reload
exec: "service": executable file not found in $PATH
```

**Comment by jjethwa** [comment]
Hi @gvenka008c 

That's weird.  It works on my containers.  You're using the jordan/icinga2 image from Docker Hub?

**Comment by jjethwa** [comment]
```
# sudo docker ps | grep icinga2
624739f4425d        jordan/icinga2:latest        "/opt/run"               2 weeks ago         Up 2 weeks          443/tcp, 0.0.0.0:80->80/tcp, 5665/tcp   icinga2
# sudo docker exec icinga2 service icinga2 status
icinga2 is running.
# sudo docker exec icinga2 service icinga2 reload
checking Icinga2 configuration.
icinga2 is running.
Reloading icinga2 monitoring daemon: icinga2.
```
