### ISSUE TITLE
Cant restart an exited container

### ISSUE THREAD

**Issue by david-61** [jjethwa/icinga2#271]
This is the first time I am using docker, and I already ran into following problem:
After I restart my server, or stop the container I cant get the exited container back started.

**This is the state if I stop the container:**
david@smon-test:~$ docker ps -f "status=exited"
CONTAINER ID   IMAGE                   COMMAND      CREATED          STATUS                        PORTS     NAMES
ecec3104946d   jordan/icinga2:latest   "/opt/run"   53 minutes ago   Exited (137) 13 minutes ago             jolly_kare

**I am trying to restart my exited container with the docker start command, and i get the following behavior:**
CONTAINER ID   IMAGE                   COMMAND      CREATED          STATUS        PORTS                                                  NAMES
ecec3104946d   jordan/icinga2:latest   "/opt/run"   25 minutes ago   Up 1 second   443/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 5665/tcp   jolly_kare

... the docker container is looking like its "active" again for about 2 or 3 seconds, then it just disappears.

I guess the problem is affiliated with the mysql password or something similar?

I am Thankful for every Help!

**Comment by jjethwa** [comment]
Hi @david-61 

Do you mind sharing the command you used to start the container?  Also, did you follow the persistence section in the readme?  https://github.com/jjethwa/icinga2#persistence

**Comment by david-61** [comment]
Hi @jjethwa 
I used the docker start command followed by the container ID of the exited container. 

Yes, I followed that persistence section and set the icinga2 user password and the root account password of my Debian server.

I think I've understood the section wrong, is it possible if you explain it how to set it?

**Comment by jjethwa** [comment]
Hi @david-61 

Do you have the initial docker run command you used to start it the first time?  If you can share that with the stripped out passwords and also the last few lines from

```
docker logs <YOUR_CONTAINER_ID>
```

**Comment by david-61** [comment]
Sorry for the late replys, I was at work

**docker run command:**
`docker run -p 80:80 -h icinga2 -t jordan/icinga2:latest`

**my secrets_sql.nv file:**
```
MYSQL_ROOT_PASSWORD=S1cher
DEFAULT_MYSQL_PASS=5uper
```
**Docker Log:**
```
Generating locales (this might take a while)...
Clearing symlinks in /etc/ssl/certs...
Generation complete.
done.
Updating certificates in /etc/ssl/certs...
137 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
[ ok ] Starting MariaDB database server: mysqld.
Pinging localhost:3306
mysqld is alive
Site 000-default already enabled
Site icingaweb2-ssl already disabled
Site icingaweb2-ssl-redirect already disabled
Pinging localhost:3306
mysqld is alive
warning/cli: Feature 'ido-mysql' already enabled.
warning/cli: Feature 'livestatus' already enabled.
warning/cli: Feature 'compatlog' already enabled.
warning/cli: Feature 'command' already enabled.
ERROR 1045 (28000): Access denied for user 'icinga2'@'localhost' (using password: YES)
run-parts: /opt/setup/50-icinga2 exited with return code 1
```

**Comment by jjethwa** [comment]
Totally get the work thing, @david-61 😄 

Thanks for the container log.  It seems like your secrets were not loaded.  The env file only gets loaded if you use docker-compose.  You'll need to add the secrets using the docker secrets command or as an environment ( -e flag) when starting the container for the first time.

**Comment by david-61** [comment]
I brought my machine to the last snapshot where I installed your Docker Image.
what would the command be if i would choose the environment option?
and what is the correct order?
1. execute docker run ??
2. docker-compose ??
3. persistence??
Sorry i am new to docker, and a annoying noob

**Comment by jjethwa** [comment]
No problem 😄 

Using docker compose might be the easiest way to get things running as it does some of the orchestration like setting up volumes and loading secrets for you.

Clone the repository and create a file secrets_sql.env, which contains the MYSQL_ROOT_PASSWORD variable.
```
git clone https://github.com/jjethwa/icinga2.git
cd icinga2
echo "MYSQL_ROOT_PASSWORD=<password>" > secrets_sql.env
docker-compose up
```

**Comment by david-61** [comment]
Hi @jjethwa
I executed the Docker compose command yesterday, and got an error:
`-bash /ist/local/bin/docker-compose: Permission denied`
I already did some research, and added the user to the docker group still same error

**Comment by jjethwa** [comment]
That looks like something particular to your setup, maybe check and see if it has executable permissions?

**Comment by david-61** [comment]
Thanks @jjethwa for the help and the Package, I really appreciate it.
Everything works like a dream now.
Best Wishes, David

**Comment by jjethwa** [comment]
Great news @david-61 🥳 

I'll go ahead and close this issue for me, but feel free to reopen it or create a new one if you have more issues
