### ISSUE TITLE
Your MySQL Database Server is running currently inside the icinga2 container. In future, the MySQL will be located in a separate container by default.

### ISSUE THREAD

**Issue by hsyedshams** [jjethwa/icinga2#273]
Hi Support out there,

I have production icinga2 server which is running in docker containers. We have currently three containers as follows:
mariadb 
icinga2_icinga2 
graphiteapp/graphite-statsd:latest

I noticed on the icinga web interface there is notification: "Your MySQL Database Server is running currently inside the icinga2 container. In future, the MySQL will be located in a separate container by default. Find more information at https://github.com/jjethwa/icinga2#moving-to-separate-mysql-container"

I checked the the above repo and found we need to set the environment variable DEFAULT_MYSQL_HOST to MySQL container.

But if i check my docker-compose.yml file its already uncommented but why its showing message. 
 - DEFAULT_MYSQL_HOST=mariadb

if i go to maridb container i and run commmand (ls -l /var/lib/mysql/) found MySQL Database:

```
`-rw-rw---- 1 mysql mysql    385024 Jan 20 14:50 aria_log.00000001
-rw-rw---- 1 mysql mysql        52 Jan 20 14:50 aria_log_control
-rw-rw---- 1 mysql mysql     14135 Nov 12 18:17 ib_buffer_pool
-rw-rw---- 1 mysql mysql 100663296 Jan 20 14:51 ib_logfile0
-rw-rw---- 1 mysql mysql  79691776 Jan 20 14:51 ibdata1
-rw-rw---- 1 mysql mysql  12582912 Nov 12 18:17 ibtmp1
drwx------ 2 mysql mysql     12288 Sep 14  2020 icinga2idomysql
drwx------ 2 mysql mysql      4096 Sep 14  2020 icingaweb2
drwx------ 2 mysql mysql     12288 Sep 14  2020 icingaweb2_director
-rw-rw---- 1 mysql mysql         0 Sep 14  2020 multi-master.info
drwx------ 2 mysql mysql      4096 Sep 14  2020 mysql
drwx------ 2 mysql mysql      4096 Sep 14  2020 performance_schema
`
```

If i go to icinga container and go to same location (/var/lib/mysql/)
`root@icinga2:/# ls -l /var/lib/mysql/
total 110624
```
-rw-rw---- 1 mysql mysql    16384 Nov 11  2020 aria_log.00000001
-rw-rw---- 1 mysql mysql       52 Nov 11  2020 aria_log_control
-rw-r--r-- 1 root  root         0 Nov 11  2020 debian-10.3.flag
-rw-rw---- 1 mysql mysql      972 Nov 11  2020 ib_buffer_pool
-rw-rw---- 1 mysql mysql 50331648 Nov 11  2020 ib_logfile0
-rw-rw---- 1 mysql mysql 50331648 Nov 11  2020 ib_logfile1
-rw-rw---- 1 mysql mysql 12582912 Nov 11  2020 ibdata1
drwx------ 2 mysql mysql     4096 Nov 11  2020 mysql
drwx------ 2 mysql mysql     4096 Nov 11  2020 performance_schema
```

My question is, if already mariadb separate container running then why i am getting notification and how to get rid of this notification.
`

Thanks

**Comment by jjethwa** [comment]
Hi @hsyedshams 

Thanks for the report.  That announcement is generated here: https://github.com/jjethwa/icinga2/blob/master/content/opt/setup/70-announcements#L40

This means that there is some data under /var/lib/mysql in the icinga2 container.  Can you confirm?

**Comment by hsyedshams** [comment]
Hi @jjethwa 

Thanks too for your prompt reply!

Yes as i mentioned above, second output of icinga container /var/lib/mysql output, there is also mysql folder.

**Comment by jjethwa** [comment]
Sorry, @hsyedshams, I misread that part. I don't think there should be data there.  Is that a volume?

**Comment by hsyedshams** [comment]
No Problem, could you please tell me which output do you need for me i am not sure about data/vloumne.
thanks!

**Comment by jjethwa** [comment]
Hi @hsyedshams 

How do you start the icinga2 container?

**Comment by hsyedshams** [comment]
docker exec -it monitor01 service icinga2 reload

**Comment by jjethwa** [comment]
Hi @hsyedshams 

That looks like the exec to force a daemon reload to pick up new configs. Do you have the original command used to start the container or was it using docker compose?

**Comment by jjethwa** [comment]
If you're only interested in deleting the message, you can check /etc/icingaweb2/announcements.ini in the icinga2 container

**Comment by hsyedshams** [comment]
Thanks! May be i miss understood, i need to verify where is our actual database is, on container icinga or maridadb.

**Comment by jjethwa** [comment]
Ah!  Got it!

Can you check /etc/icinga2/features-available/ido-mysql.conf in the icinga2 container?  That shows the database connection information.  Is it local or the mariadb container?

**Comment by hsyedshams** [comment]
Hi, sorry for being late reply!

here is output from icinga container (/etc/icinga2/features-available/ido-mysql.conf) :
/**
 * The db_ido_mysql library implements IDO functionality
 * for MySQL.
 */

library "db_ido_mysql"

object IdoMysqlConnection "ido-mysql" {
  user     = "icinga2"
  password = ""
  host     = ""
  port     =  3306
  database = "icinga2idomysql"
}

**Comment by jjethwa** [comment]
np @hsyedshams 

Unfortunately that didn't help.  Inside the cointainer, can you run:

```
supervisorctl status all
```

**Comment by hsyedshams** [comment]
Ok, let's find it here.

Output from the icinga container:
root@icinga2:/# supervisorctl status all
apache2                          RUNNING   pid 1523, uptime 73 days, 14:53:20
director                         RUNNING   pid 1522, uptime 73 days, 14:53:20
fatalservice                     RUNNING   pid 1521, uptime 73 days, 14:53:20
icinga2                          RUNNING   pid 3574936, uptime 0:00:04
mysql                            RUNNING   pid 1524, uptime 73 days, 14:53:20

**Comment by jjethwa** [comment]
Thanks, that does seem like a mariadb process is running.

One more, do you mind sharing (with sensitive information removed) the contents of /etc/icingaweb2/resources.ini

**Comment by hsyedshams** [comment]
Thanks! So it means mariadb is running inside icinga container. So how we can switch database to separate maridb container. 

Here we go 

[icingaweb_db]
type = "db"
db = "mysql"
host = mariadb
port = 3306
dbname = icingaweb2
username = xxxxxx
password = xxxxxxxxxxx
prefix = "icingaweb_"
charset = "utf8"
persistent = "0"

[icinga_ido]
type = "db"
db = "mysql"
host = mariadb
port = 3306
dbname = icinga2idomysql
username = xxxxxx
password = xxxxxxxxxxxx
charset = "utf8"
persistent = "0"

[director]
type = "db"
db = "mysql"
host = mariadb
port = 3306
dbname = icingaweb2_director
username = xxxxxx
password = xxxxxxxxxxxxx
charset = "utf8"
persistent = "0"
`

**Comment by jjethwa** [comment]
This is the output I needed to see! 😄   The host is correctly set to the mariadb container.  It looks like the local mariadb started up at some point, but it doesn't seem like you need to worry about it being active.

**Comment by hsyedshams** [comment]
If the host already set maridb container, it means pointing to host mariadb container, so for i can understand here.

But why i am getting in the web "our MySQL Database Server is running currently inside the icinga2 container. In future, the MySQL will be located in a separate container by default."

**Comment by jjethwa** [comment]
The check to add the announcement is very basic, it just looks for the existence of any file inside the mysql/mariadb directory locally: https://github.com/jjethwa/icinga2/blob/master/content/opt/setup/70-announcements#L40

Since mariadb started locally at some point in time, probably before you transferred the data to the separate container, the old database files still exist (locally).  I think it's safe just to remove the announcement.

**Comment by hsyedshams** [comment]
Thank you. 
Ok cool idea would be remove the announcement, could u please point me how to remove the announcement.

**Comment by jjethwa** [comment]
Announcements are added under /etc/icingaweb2/announcements.ini

**Comment by hsyedshams** [comment]
Thanks! 
So i just need to comment message line and reload the icinga service.
So as per our whole discussions, we checked file (/etc/icingaweb2/resources.ini) and found database running on seperate  mariadb container. And notification is giving because mariadb started locally at some point but now database has separate container for storing data.
It means i dont need to configure anything on icinga container to use mardia container as database, its already confgiured.

`author = "xxxxxx"
message = "Your MySQL Database Server is running currently inside the icinga2 container. In future, the MySQL will be located in a separate container by default. Find more information at https://github.com/jjethwa/icinga2#moving-to-separate-mysql-container"
start = "xxxxxxxxxxxxxx"
end = "xxxxxxxxxxxxxxxxx"
hash = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
`

Thanks for your overall help so far.

**Comment by jjethwa** [comment]
Hi @hsyedshams 

That summarises it perfectly.  Just comment out that section and you should be good to go 😄
