### ISSUE TITLE
Corrupt File?

### ISSUE THREAD

**Issue by david-61** [jjethwa/icinga2#274]
Hi everyone,
I ran into this following issue:
I installed this docker image and executed it with following command:
docker run -p 80:80 -h icinga2 -v smon-test:/etc/icinga2 -t jordan/icinga2:latest

I got following log after executing the command:
--------------------------------------------------------
```
PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/var/lib/mysql'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl

Please report any problems at http://mariadb.org/jira
```
--------------------------------------------------------
I ran this following command:

```/usr/bin/mysql_secure_installation```
--------------------------------------------------------

I got following output:

```
FATAL ERROR: Could not find /usr/bin/my_print_defaults

If you compiled from source, you need to run 'make install' to
copy the software into the correct location ready for operation.

If you are using a binary release, you must either be at the top
level of the extracted archive, or pass the --basedir option
pointing to that location.

```
--------------------------------------------------------
and this is a small snippet from the file my_print_defaults:

```
^?ELF^B^A^A^@^@^@^@^@^@^@^@^@^C^@>^@^A^@^@^@�^X^B^@^@^@^@^@@^@^@^@^@^@^@^@`�5^@^@^@^@^@^@^@^@^@@^@8^@^K^@@^@^\^@^[^@^F^@^@^@^D^@^@^@@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@@^@^@^@^@$^C^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@d^C^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@m^B^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@�^A^@^@^R^@^@^@^@^@^@^@^@^@^@^@$^@^@^H^@�^D^@^@^P^@^@^@���^F^@^@^G^@�^D^@^@^P^@^@^@���^F^@^@^F^@�^D^@^@^P^@^@^@u^Zi     ^@^@^E^@�^D^@^@^P^@^@^@t^Yi     ^@^@^B^@�^D^@^@^@^@^@^@�^D.^@^@^@^@^@^H^@^@^@^@^@^@$.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@^P
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@(
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@8
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@@
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@P
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@X
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@h
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@p
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@�
.^@^@^@^@^@^H^@^@^@^@^@^@^@��^E^@^@^@^@^@�
.^@^@^@^@^@^H^@^@^@^@^@^@^@u�^E^@^@^@^@^@

```

**Comment by jjethwa** [comment]
Hi @david-61 

Thanks for reporting the issue.  Do you mind trying to start the container up without the volume to see if it comes up ok?  You shouldn't need to have to run any commands to get things going with the out of the box setup.

**Comment by david-61** [comment]
Hi @jjethwa, I just executed
`docker run -p 80:80 -h icinga2 -t jordan/icinga2:latest
`
on a snapshot, it works good like mymodified command, but this file is still corrupt.
I tought I had to modify this file because I still have persistence problems on my test machine.
Maybe I have understanded your documentation wrong?
I created a user on my Debian system called Icinga and set a Password
and I entered the pass for the icinga and root user into the file called secrets_sql.env
and executed docker compose. everything works, until the restart.

After I restart my System I cant get acess to Icingaweb2, but the container starts according to docker
I cant understand this : /

**Comment by jjethwa** [comment]
Hi @david-61 

This was just to prove that the container is working correctly and there are no corrupted files within it.

Let's go through the docker compose steps one more time.

1. Clone the repo to the target machine: git clone https://github.com/jjethwa/icinga2.git
2. cd icinga2
3. echo "MYSQL_ROOT_PASSWORD=<ROOT_PASSWORD>" > secrets_sql.env
4. (optional) echo "DEFAULT_MYSQL_PASS=<ICINGA_DATABASE_PASSWORD>" >> secrets_sql.env
5. docker-compose up

Can you verify that works and you can restart the container via docker compose?

**Comment by david-61** [comment]
Thanks for the tip, now I managed to get icingaweb2 after restart.
my fault was: I havent executed docker compose once after the restart. 🤦🏻‍♂️
Now everything is up and running
Thank you for your Help @jjethwa.
