### ISSUE TITLE
Permissions building the image

### ISSUE THREAD

**Issue by bbkz** [jjethwa/icinga2#280]
Hi,

when i checkout the repo, no file permissions will be set. So after building the image will not work.

For example the entrypoint `/opt/run` is not executable. It seems not to be the only file because even when i set this one to be executable it don't work yet.

Can you create a additional run part to set the correct permissions for the content files?

Yours,
bbk

**Comment by jjethwa** [comment]
Hi @bbkz 

That's strange, the file is executable.  Are you using Linux to build?

**Comment by bbkz** [comment]
oh... right, sorry. I had copied the files around and forgot to copy the permissions.
