### ISSUE TITLE
DockerFile issue: Access denied for user root (using password NO)

### ISSUE THREAD

**Issue by nicolafort** [jjethwa/icinga2#282]
Hello,

I saw already that is a FAQ, but even if I follow all posts, I'm not able to build container from GitHub docker file.

If I create a single docker with everything embedder (docker run) it works nicely, but I try version with separate container for MariaDB, it keeps failing due authentication error on mariaDB container.

As suggested I added  
DEFAULT_MYSQL_PASS and MYSQL_ROOT_PASSWORD variables (I tried inside secrets_sql.env, and inside docker-file either), from a fresh install but I still get same error.

I also checked inside configuration file (inside container), and I can see that docker-compose script correctly fills file in proper way (I can see my password inside configuration files inside persisted volume) but, still it doesn't work.

I also replace mariaDB with mysql and in that case it works fine, but it stops later because mysql doesn't support some crypto libraries that are required by setup, but at least I don't have authentication error anymore.

Might be that MARIADB and MYSQL variables (actually in docker file we are specifying MYSQL variables even though we use mariaDB later) are not anymore 100% compatible (so password field s not used correctly).

I just trying to guess, because my skills are very limited.

Regards.

**Comment by nicolafort** [comment]
Hi

Yes, actually I’m using docker file you can download from:

git clone https://github.com/jjethwa/icinga2.git


When I tried to use mysql instead, I just replaced inside docker file image reference from mariadb -> mysql.

**Comment by jjethwa** [comment]
I would stick with mariadb since mysql won't have all of the necessary libraries that are needed.  

If you docker exec into the mariadb container, can you log in with the credentials you set in the env file?

**Comment by nicolafort** [comment]
Yes I can.

From maria db container:

administrator@docker:~/docker/icinga2$ sudo docker exec -it  c8f6f6059991 /bin/bash
root@c8f6f6059991:/# mysql -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 27
Server version: 10.7.3-MariaDB-1:10.7.3+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| icinga2idomysql    |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.004 sec)

**Comment by jjethwa** [comment]
k so the root account password looks set correctly, do you mind trying the icinga2 user?  If that's good, then we need to doublecheck if the password was set correctly in the icinga2 container

**Comment by nicolafort** [comment]
I can confirm to you that from inside mariadb container it works also icinga2 user:

administrator@docker:~/docker/icinga2$ sudo docker exec -it  3e80ecc8f0fa /bin/bash
root@3e80ecc8f0fa:/# mysql -u icinga2 -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 27
Server version: 10.7.3-MariaDB-1:10.7.3+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>


***********************************

Checking inside icinga2 container it seems that also password is set correctly (assuming I'm looking inside right file)

vi /icinga/etc/icinga2/features-enabled/ido-mysql.conf


**
 * The db_ido_mysql library implements IDO functionality
 * for MySQL.
 */

library "db_ido_mysql"

object IdoMysqlConnection "ido-mysql" {
  user     = "icinga2"
  password = "mypassword"
  host     = "mysql"
  port     =  3306
  database = "icinga2idomysql"
}
~

**Comment by jjethwa** [comment]
Thanks for that, that's the correct file.  Can you share the portion of the log that shows the authentication error?

**Comment by nicolafort** [comment]
[icinga.log](https://github.com/jjethwa/icinga2/files/8387430/icinga.log)

Here is log file.

I have just the feeling, that somehow container (Icinga) is not considering password value when it tries to connect to mariaDB container even though it is correctly set inside config file...

**Comment by jjethwa** [comment]
I can't reproduce the issue, so I think it's something strange with your setup.  Hopeful we'll figure it out with a bit more troubleshooting. 

I see this entry in the log you attached:
```2022-03-31  8:18:06 23 [Warning] Access denied for user 'root'@'172.18.0.2' (using password: NO)```

Let's look at the icinga2 application logs next.  In the icinga2 container, it'll be under /var/log/icinga2

**Comment by Acr0most** [comment]
I Think i fixed it that way - but actually default cron wont work:

the fail is this check:


`vi content/opt/setup/55-cron +5`

```

#!/bin/bash
if [ ! -f "/etc/cron.d/icinga" ]; then
 [...]
fi
```

/etc/cron.d/icinga is a directory, so the `cat >` in line 8 wont work and a error is thrown.

by adding `&& [ ! -d "/etc/cron.d/icinga" ]` I can run icinga2 in docker-compose.

Where should be the cron-content stored? Or why is icinga already a directory?

**Comment by jjethwa** [comment]
@Acr0most can you provide details on what you did to fix the original issue?

For the cron issue, I think we can just change the path of the cron file

**Comment by Acr0most** [comment]
Well my log and the log from the opener are the same:

```
icinga2_1   | warning/cli: Feature 'graphite' already enabled.
icinga2_1   | => Copying icinga cronfile for /etc/cron.d
icinga2_1   | /opt/setup/55-cron: line 8: /etc/cron.d/icinga: Is a directory
icinga2_1   | run-parts: /opt/setup/55-cron exited with return code 1
icinga2_icinga2_1 exited with code 1
```

The Problem isnt the mysql connect error - it runs also with this error.

The icinga2 container exits because the error code /opt/setup/55-cron returns. And this Happens because inside the container /etc/cron.d/icinga is alredy a directory - but should be a file or non existing. 

So my fix only Checks also if it is a directory- so the 55-cron does nothing, returns no error response and everything works- only the cron file is missing.

**Comment by jjethwa** [comment]
Thanks for the info, @Acr0most 

Looks like there might be a slight difference in how versions are handling setting up the volume.  Please give it a try with latest and see if it resolves that particular issue 😃

**Comment by jjethwa** [comment]
Great news!  Thanks @nicolafort and @Acr0most 👍
