### ISSUE TITLE
Environment variable to specify icinga2 `log-level`

### ISSUE THREAD

**Issue by silverwind** [jjethwa/icinga2#289]
`log-level` would be a nice config option, it is exposed only as a CLI option:

```
$ icinga2 --help | grep log-level -A2
  -x [ --log-level ] arg    specify the log level for the console log.
                            The valid value is either debug, notice,
                            information (default), warning, or critical
```

Would is be possible to provide a `ICINGA2_LOG_LEVEL` variable for it, defaulting to `information`? I cursorly looked through the code, but could am not sure I have the right place where `icinga2` is being ran.

**Comment by jjethwa** [comment]
Hiya @silverwind 

The daemon is started by: https://github.com/jjethwa/icinga2/blob/master/content/opt/supervisor/icinga2_supervisor#L18

I'm wondering if setting the FileLogger Object might be a better option for you?  https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#objecttype-filelogger

**Comment by silverwind** [comment]
> The daemon is started by: https://github.com/jjethwa/icinga2/blob/master/content/opt/supervisor/icinga2_supervisor#L18

Ah, I see it forks out to `/etc/init.d/icinga2` where `DAEMON_ARGS` would have to be modified to include the `log-level`argument. I thin this init script is not yet replaced by your tooling, so it would need to be I guess.

> I'm wondering if setting the FileLogger Object might be a better option for you? https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#objecttype-filelogger

Not really unfortunately, it seems to only configure an additional file output, not control the main output. I tried setting it to `/dev/stdout` but that just crashes Icinga on startup with `Could not open logfile '/dev/stdout'`.

**Comment by jjethwa** [comment]
Yeah, I haven't touched the init script, but I'll have a look on Monday and see if there's an easy way to add in the modification without having to maintain the init script in this repository as well 😃

**Comment by silverwind** [comment]
Thanks. To clarify, this is only about the stdout log, which is really the only log I care about 😉

**Comment by jjethwa** [comment]
Hi @silverwind 

Just pushed latest and 2.13.5 with your suggestion.  Please let me know if it works for you 😄

**Comment by silverwind** [comment]
Works nicely, thanks!

During startup, there's some stuff logged that apparently bypasses the `log-level`, but that' definitely to blame on Icinga itself 😆.

**Comment by jjethwa** [comment]
Good to know, thanks 🤣
