### ISSUE TITLE
Error : GlobFilter

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#29]
Hello 

I just created a new container with your last version of Icinga.

But I have a problem when I want to check the detail of a host ( just a click on the default host when you start Icinga). I have the following error : 

**Fatal error: Class 'Icinga\Util\GlobFilter' not found in /etc/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php on line 507**

I also have the problem when I had a host.

Do you know how to fix it ? 

Another question, Graphite is not in icinga anymore ? 

Thank you :)

**Comment by Quentinvarquet** [comment]
Edit : You can try it here : http://91.121.64.81:8080/icingaweb2 (I just did the docker run command on your readme and I added a new host. The problem is also here with the default hosts.conf

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Unfortunately the link does not work for me, but I was able to reproduce the issue locally.  Sorry about that!  I'll look into it :)

**Comment by Quentinvarquet** [comment]
Hello,

Yes sorry I put off my Docker container when I left work by mistake :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

This has been resolved: https://github.com/jjethwa/icinga2/commit/fd1caaf51078d9a4a98294d0482610fa44089d66

The latest container and 2.4.7 both have the fix.  Thanks,

Jordan

**Comment by Quentinvarquet** [comment]
Morning @jjethwa,

It was fast ,I just tried. Perfect ! 

Thank you :-)
