### ISSUE TITLE
permission error on /var/cache/icinga2 folder under Windows

### ISSUE THREAD

**Issue by WingsLikeEagles** [jjethwa/icinga2#292]
On a Windows host, when running the container an error occurs:
```icinga2     | [2022-09-09 13:42:09 +0000] critical/cli: Could not create temporary objects file: Error: Function call 'chmod' for file '/var/cache/icinga2/icinga2.debug.4fkWV3' failed with error code 1, 'Operation not permitted'```

This does not happen on a Mac.  Suspect the permissions on the folder /var/cache/icinga2 are causing the error. I noticed the /var/log/icinga2 permissions are being modified in the Dockerfile, but not the /var/cache/icinga2.

**Comment by jjethwa** [comment]
Hi @WingsLikeEagles 

Thanks for the report. I haven't seen this issue on Linux or on Windows using Docker for Windows (WSL2).  Are you using a volume for /var/cache/icinga2 perhaps?
