### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by preske87** [jjethwa/icinga2#298]
The documentation on docker hub (https://hub.docker.com/r/jordan/icinga2) and here (https://github.com/jjethwa/icinga2) are not in sync.

Documentation on docker hub does not mention the variable `CUSTOM_POST_INSTALLATION_SCRIPT`.

Maybe also the docker hub page could link to this repo

**Comment by jjethwa** [comment]
Hi @preske87 

Sorry about that, Docker HUb used to keep it in sync from the git repo.  I'll update it now and also link to the repo README
