### ISSUE TITLE
Dockerfile: deb http://packages.icinga.org/debian does not exist anymore (?)

### ISSUE THREAD

**Issue by hansij66** [jjethwa/icinga2#299]
I am building my own docker image from Dockerfile.

Line 68:
`&& echo "deb http://packages.icinga.org/debian icinga-$(lsb_release -cs) main" > /etc/apt/sources.list.d/icinga2.list \`

http://packages.icinga.org/debian does not exist (anymore)?

I can change this line to 
http://packages.icinga.com/debian (which does exist)...but then I get following dependency error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icingaweb2 : Breaks: icingaweb2-module-doc (< 2.11.4-1+debian11) but 2.11.3-2.bullseye is to be installed
 icingaweb2-module-doc : Depends: icingaweb2 (= 2.11.3-2.bullseye) but 2.11.4-1+debian11 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by jjethwa** [comment]
Hi @hansij66 

Sorry about that, it looks like I missed the TLD update.  I've made that change and also a few other tweaks that were needed after the repository update.  Please pull the updates and let me know if you have any issues 😓

**Comment by hansij66** [comment]
Thanks; solutions works! Thanks.
