### ISSUE TITLE
DEBIAN_SYS_MAINT_PASSWORD not working

### ISSUE THREAD

**Issue by The-Judge** [jjethwa/icinga2#3]
Hi, in your README, you name DEBIAN_SYS_MAINT_PASSWORD variable to set. In your "run" script at line 20, you do not respect this Variable, but force a random one.

**Comment by jjethwa** [comment]
Hi The-Judge,

Thanks for bringing it to my attention.  I've modified the run script to respect the passed value:

https://github.com/jjethwa/icinga2/commit/0f4dab2629fc6106845b6dbf41756bb71b72c801

Thanks again,

Jordan
