### ISSUE TITLE
Volumes file system

### ISSUE THREAD

**Issue by ismaello** [jjethwa/icinga2#30]
>
mkdir -p /tmp/icinga 
docker run  --link graphite:graphite -v /tmp/icinga:/etc/icinga2  -e ICINGA2_FEATURE_GRAPHITE=true -e ICINGA2_FEATURE_GRAPHITE_HOST=graphite -e ICINGA2_FEATURE_GRAPHITE_PORT=2003 -e ICINGA_PASSWORD="icinga" -e ICINGA_WEB_PASSWORD="icinga_web" -p 5665:5665 --name icinga3 -t jordan/icinga2:latest
chown: cannot access '/etc/icinga2/features-available/ido-mysql.conf': No such file or directory

I did the same test with another images (mysql, graphite, ...) and everything work fine.

**Comment by jjethwa** [comment]
Hi @ismaello 

Thanks for reporting the issue.  It looks like you're using an empty volume for /etc/icinga2 ?  What I suggest for most users is starting the container without the volume then using docker cp to copy the configs and other data over to the host then stopping and starting the container with the volume.

Please let me know if this works for you.  Thanks :)

**Comment by ismaello** [comment]
Yes, it's alive. 
Thanks.
