### ISSUE TITLE
MySQL user 'root' has no password 

### ISSUE THREAD

**Issue by DrDeef** [jjethwa/icinga2#300]
Well hello there,

quick question, I've an issue with a stopped container which I made changes to.

The first run states that:
===================================================================
MySQL user 'root' has no password but only allows local connections

but I've created an secrets_sql.env containing MYSQL_ROOT_PASSWORD=<somestring> which stated with:
docker run --env-file ./secrets_sql.env -p 8888:80 -h icinga2 -t jordan/icinga2:latest

Can someone tell me what I am doing wrong here?

**Comment by jjethwa** [comment]
Hi @DrDeef 

You should be able to connect to the mariaDB/mySQL database using the password you set once the container is running and docker exec'ing into it.  Please let me know if that works.

**Comment by DrDeef** [comment]
Thanks bro, works like a charm, was to stupid to pass it right into the container... :)
