### ISSUE TITLE
Disable Icinga default host and service

### ISSUE THREAD

**Issue by TheDoDoo** [jjethwa/icinga2#301]
Hello everyone,
Is there a way to deactivate the default Icinga host and service?

![image](https://github.com/jjethwa/icinga2/assets/96340450/82fcd728-3ec9-4a14-89c4-00598efe1171)
![image](https://github.com/jjethwa/icinga2/assets/96340450/c2565095-c09f-43b7-bae1-1594de26d3b3)

**Comment by jjethwa** [comment]
Hi @TheDoDoo 

Icinga includes the master and satellites by default so you are alerted if they run into issues.  You should use a volume or database to save your configs permanently.
