### ISSUE TITLE
TimePeriode not working ?

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#34]
Hello,

I wanted to create a custom time period.

Here is my **timeperiod.conf** file : 

```
object TimePeriod "custom-period" {
  import "legacy-timeperiod"

  display_name = "Custom Period - 6 am to 8 pm"
  ranges = {
    "monday" 	= "06:00-20:00"
    "tuesday" 	= "06:00-20:00"
    "wednesday" = "06:00-20:00"
    "thursday" 	= "06:00-20:00"
    "friday" 	= "06:00-20:00"
  }
}
```

Now, my **notification.conf**

```
apply Notification "mail-icingaadmin" to Host {
  import "mail-host-notification"

  interval = 0
  user_groups = [ "icingaadmins" ]
  states = [ Up, Down ]
  times.begin = 20m # Send an email after 20 minutes
  types = [ Problem, Recovery, Custom,
            FlappingStart, FlappingEnd,
            DowntimeStart, DowntimeEnd, DowntimeRemoved ]

  period = "custom-period"
  assign where host.vars.criticity == "No" # only for low criticity hosts

}
```

The problem is, I still have many emails during the night after 8pm and I really don't understand why... Do you have an idea ?

Edit : I am using icinga v2.3.0-193-g3eb55ad (june 2015...). I tried on the last version of icinga (on my own server) from your hub and it's work, do you have any idea how to fix it on my version ?

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Not sure why it's not working in the version you are using, but it could be because there was a bug in the older version that is now fixed.  We really need to get you upgraded :package: 

Are you trying to make it so Icinga only sends notifications during the daytime hours or something else?

**Comment by Quentinvarquet** [comment]
Hello !

> We really need to get you upgraded :p


Trust me I know it, I also have to update my docker version (ho yes...) but for now it's not possible at all   even if i really want it ! (many applications in "production" ...)

>  there was a bug in the older version that is now fixed

Yes I found some informations about it but I didnt try to fix it by myself on my production server.


> Are you trying to make it so Icinga only sends notifications during the daytime hours 

Exactly, I tried to play with the downtimes (temp fix) but it's not working well (not very stable).

I will really have to upgrade it I think this is the only solution.

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

I can try to help if you run into issues :)  Try copying your volumes to a test server and starting a new icinga container there as a quick test.  You'll probably need to upgrade the MySQL schema: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/upgrading-icinga-2?highlight-search=mysql#upgrading-mysql-db

**Comment by Quentinvarquet** [comment]
Hi @jjethwa I really appreciate but I will have to update it !

Thank you :)

**Comment by Quentinvarquet** [comment]
Hello,

We will finally update it this month ! :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

That's great!  Wishing you a smooth update🙂
