### ISSUE TITLE
Question : Menu for user

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#36]
Hello,

I finally have the last version of your container on my server  ! :-) 

I just have a question. The administrator is using the icingaadmin account and I created 4 more users (they are all in a UserGroups).

I want them to have the same view as the administration (same menu on the left) but without the "configuration" menu.

I want : 

Dashboard
Problems
Overview
History
Reporting
Documentation

Do you know how to do this ? Because is the Role permission I only have choice with ; 

- Allow everythings (ok they see everything but I don't want the configuration parts)
- Allow to share navigation items
- Allow to adjust in the preference ...
- Allow config access
- Allow access to module setup
- Allow access to module translation

Thank you !

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

That's great news! :)

I believe not giving the users the Allow config access should work.  They might be able to read, but not modify changes.  Let me know if it does not work for you.

**Comment by Quentinvarquet** [comment]
Hello, I found it (I guess).

I added in icingaweb2/roles.ini : 

```
[Users]
groups = "network-team"
permissions = module/monitoring, monitoring/command/*
```

Than they have the same menu as the administrator without the config.

**Comment by jjethwa** [comment]
Thanks, @Quentinvarquet 

That's good to know 🙂
