### ISSUE TITLE
Can't Start Mysql

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#38]
Hello,

After 2 month, the mysql service in my icinga container can't start anymore.

I have this error : 

> /etc/init.d/mysql: ERROR: The partition with /var/lib/mysql is too full! ... failed!

If I check my disk in my container : df -l

![image](https://cloud.githubusercontent.com/assets/7962157/16451470/975be4a4-3e03-11e6-8e1e-3d251f9a7273.png)

Do you have any idea about this problem ?

Thank you

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Is there enough space on the host that contains the/var/lib/mysql volume?

**Comment by Quentinvarquet** [comment]
Yes,  and the folder var/lib/mysql is only 300 MO...

It's*a volume on my host,  the disk has 1000 Go.  I already don't
understand at all!

**Comment by jjethwa** [comment]
Hmm, that's really strange.   If your host has enough space, there is no limitation.  Can you check the ownership of the volume directory and files?  Also,  make sure the volume is getting mounted with r/w permission 😞

**Comment by jjethwa** [comment]
Also, are you running the container via the docker command only or using some sort of swarm management?

**Comment by Quentinvarquet** [comment]
Hello, No I am only using docker and Docker-Compose.

It's on my personnal server, I will try to find a solution this week end because I really don't understand at all !

Thank you

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Neither of those should limit the size of the volume :(

Can you try running a docker inspect on your container and see what is shown under the Mounts section of the JSON output?

**Comment by Quentinvarquet** [comment]
Hello @jjethwa 

I found the problem tonight (I guess). I really have a problem with the /dev/root partition on my host (not only in my container). This partition is totally full (20 GO). I don't know why but the problem is really here. No problem with the container !

I can close :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Good news!  Good luck with your issue :)
