### ISSUE TITLE
Encoding in the last version of Icinga

### ISSUE THREAD

**Issue by Quentinvarquet** [jjethwa/icinga2#41]
Hello ! :-) 

I updated all my icinga2 production container.

But do you know if someting changed with the encoding ? I have many problems because of this.

For example, my icinga container has some services  and they check files.

For example my service will do "rm /data/dump/my-file.conf"

Icinga2 is telling me the file doesn't exist but I if I do the command by myself it works.

So I checked the command from Icinga. The command is exactly the same as I did manually.

**manually :** rm /data/dump/my-file.conf     -> It work's
**Icinga2 :** rm /data/dump/my-file.conf     -> my-file.conf  No such file or directory

So I just did a echo **my-file.conf | od -x -c** and here is what I got.

For my manually command, the out put is :  

```
echo my-file.conf | od -x -c
0000000    796d    662d    6c69    2e65    6f63    666e    000a
          m   y   -   f   i   l   e   .   c   o   n   f  \n
0000015
```

So it's fine.

From the Icinga2 command 

```
echo my-file.conf | od -x -c
0000000    796d    e22d    8b80    6966    656c    e22e    8b80    6f63
          m   y   - 342 200 213   f   i   l   e   . 342 200 213   c   o
0000020    666e    000a
          n   f  \n
0000023

```

We can see I have a big problem with the command from Icinga, the encoding is not good at all.

Do you have any information about this ? Someting changed with the last version ? 

Also, everything are working with the command " by_ssh ". And it look like the encoding problem is from this command...

Thank you !

**Comment by jjethwa** [comment]
Hi,

What version were you using previously?  Are your confirmation files UTF-8 encoded?

**Comment by Quentinvarquet** [comment]
Hey, 

If I have a good memory I used the version Icinga 2.3.4 or 2.3.5 (maximum)

Yes my files are UTF-8 encoded.

If I take my commmand directly from my service.conf and I paste it, the **my-file.conf | od -x -c** is also good, like when I did it manually...

I really feel like it's from the " by_ssh " command in Icinga.

I can show you another example, it did not work too

`object CheckCommand "by_ssh_cpu" {
	import "by_ssh"

	vars.by_ssh_command = [ PoolerPluginDir + "/check_snmp_load.pl -H $address$ -C $snmp_community$ -w $snmp_warn$ -c $snmp_crit$ -f" ]
	vars.by_ssh_identity = PoolerIdentity
	vars.by_ssh_logname = PoolerLogname
	vars.by_ssh_address = PoolerAddress
	vars.by_ssh_port = PoolerPort
	vars.by_ssh_timeout = 20
}`

The only output from icinga is "check_snmp_load.pl no found". Like before, if I did it manually it's works

I will try to find why, I never got this :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

Hmm, I'll have to look at this in more detail when I get back on Monday🙂  For the by_ssh_cpu conf, what happens if you hardcode the path to the check_snmp_load.pl script?

**Comment by Quentinvarquet** [comment]
Hello, I still have the same problem. Here is the message from icinga2 : 

Remote command execution failed: bash: /home/icinga/plugins/icinga/check_​snmp_​load.​pl -H my_server -C my_snmp_community -w 70 -c 85 -f: No such file or directory

if I copy the message from Icinga, and I do an echo on it, I still have a encoding problem : 


```
echo check_​snmp_​load.​pl | od -cx
0000000   c   h   e   c   k   **_ 342 200 213**   s   n   m   p   _ 342 200
           6863    6365    5f6b    80e2    738b    6d6e    5f70    80e2
0000020 213   l   o   a   d   **. 342 200 213**   p   l  \n
           6c8b    616f    2e64    80e2    708b    0a6c
```

**Comment by Quentinvarquet** [comment]
Hello, I have some news.

I tried a fresh new installation (this time on my personnal server).

I also have this problem.

I tried to use the " by_ssh" commands in Icinga from my personal server to another personal server and I have exactly the same problem !

I configured everything manualy in this new Icinga and look when I am using the by_ssh, if I do an  echo from the Icinga2 message I still have the same problem  : 

```
echo check_​snmp_​load.​pl | od -cx
0000000   c   h   e   c   k   _ 342 200 213   s   n   m   p   _ 342 200
           6863    6365    5f6b    80e2    738b    6d6e    5f70    80e2
0000020 213   l   o   a   d   . 342 200 213   p   l  \n
           6c8b    616f    2e64    80e2    708b    0a6c
```

It really look like it's an icinga2 bug from the last version. What do you think ?

**Comment by lippser** [comment]
Hi,

This is a Web 2 issue. The plugin output HTML contains invisible zero width space characters. This helps browsers to "nicely" break lines but screws copy and paste unfortunately. Could you please open an issue for Web 2 at dev.icinga.org? I'll then try to fix this asap.

Best regards,
Eric

**Comment by Quentinvarquet** [comment]
Hello @lippser thank you for your answer ! 

I will open the issue. Thank you very much, it was a very important issue for my production instance.

It's weird because before I update my icinga version i never had this kind of problem.

Thank you very much.

**Comment by jjethwa** [comment]
Thanks @lippser :)

@Quentinvarquet  I'm back to my computer finally.  Thanks for your patience :)

**Comment by Quentinvarquet** [comment]
No problem ! I guess I am not really lucky... :-) I close I will keep the issue updated when it's fixed

**Comment by Quentinvarquet** [comment]
Hello @jjethwa 

FYI, the issue is solved (patch available).

Link : https://dev.icinga.org/issues/12134#change-52746

They will probably add it for the next version of icingaweb2 :-)

**Comment by jjethwa** [comment]
Hi @Quentinvarquet 

That's great news and thanks for linking me to the issue :)

**Comment by Quentinvarquet** [comment]
Hi, 

It should be fixed in the last version of Icinga,  I will try today and let you know :)

**Comment by jjethwa** [comment]
That'll be awesome! :)

**Comment by Quentinvarquet** [comment]
I confirm, it's solved :)

**Comment by jjethwa** [comment]
Yay! :)
