### ISSUE TITLE
Icinga Web cannot connect to database with auto-generated password

### ISSUE THREAD

**Issue by rgov** [jjethwa/icinga2#46]
If I start your image without specifying passwords, they're generated for me ("If passwords are not supplied, they will be randomly generated and shown via stdout").

```
$ docker run -p 8080:80 --name icinga2 -t jordan/icinga2:latest
...
===================================================================
MySQL user 'root' has no password but only allows local connections
MySQL user 'debian-sys-maint' password set to EFIgc7S3kHsvnKW
MySQL user 'icinga' password set to q53vbEupz2UX0bK
```

However then when I navigate to the web interface, I get:

```
PDO Connection Error: SQLSTATE[28000] [1045] Access denied for user 'icinga_web'@'localhost' (using password: YES)
```

**Comment by rgov** [comment]
Ah, I see. The site at `/icinga-web` gives the above error, but `/icingaweb2` works. Is that expected?

**Comment by jjethwa** [comment]
Hi @rgov 

Sorry, about the bug.  icingaweb2 was still in the RC stage when I first started working on this container.  Since mostly everyone has moved to the newer interface, I stopped checking  icinga-web.  I'll get that sorted :)

**Comment by jjethwa** [comment]
Hmm on second thought, I'm going to remove icinga-web from the latest release as it looks like it's in maintenance mode now.  The fun modules are all in icingaweb2 anyway :p
