### ISSUE TITLE
Upgrade overwrite existing settings and password

### ISSUE THREAD

**Issue by aleliga** [jjethwa/icinga2#50]
Hi All,
Last upgrade of container overwrite the settings in the existing volumes, when run the container
It need to be restored from a backup
Seems that the run process don't "understand" that there is already a previous configuration

Ciao
Alessio

**Comment by jjethwa** [comment]
Hi @aleliga 

Really sorry to hear about that.  Can you provide some more information?  What tag were you using and which one did you update to?  What settings were overwritten?  /etc/rundeck or others?  Thanks :)

**Comment by aleliga** [comment]
Hi @jjethwa 
I'm upgrading to latest, from a 2.5.3 image, but i haven't the tag

jordan/icinga2         latest              195ed575fe77        7 weeks ago         564.8 MB
jordan/icinga2         <none>              1ec3d4d9bc6f        11 weeks ago        573.1 MB

jordan/icinga2         <none> sha256:8087f5dc56968463bd6d77fee602b8c07e4f30021774e68ef4c744bca5884cca

the overwritten settings are /etc/icingaweb2, /etc/icinga2... all the mounted volumes
TY too

**Comment by jjethwa** [comment]
Hi @aleliga 

Thanks for the information.  I tracked it down to the last few commits.  Some logic was added to handle cases where the container with empty config volumes.  You should now have a CONFIGURED file (0 bytes) in your /etc/icinga2 and /etc/icingaweb2 directories which will stop the configs from being overridden again.   I'll see if I can add another check to stop this from happening again.

**Comment by jjethwa** [comment]
Hi @aleliga 

This should be fixed in the latest build.  I ran some tests and it seems to be working.  Please let me know and close the issue if it's resolved :)

**Comment by bebehei** [comment]
The initial description of this issue does not match the behavior of the image anymore. Closing this.
