### ISSUE TITLE
docker run without volume for /etc/icingaweb2 breaks

### ISSUE THREAD

**Issue by bebehei** [jjethwa/icinga2#61]
Invoking docker with `docker run --rm -ti jordan/icinga2`:

Icinga fails to setup correctly, as /etc/icingaweb2/ contains some files and `[ $(ls -A /etc/icingaweb2)]` returns actually true in [`/opt/run`](https://github.com/jjethwa/icinga2/blob/master/content/opt/run#L40):

```
root@50f77b52b865:/etc/icingaweb2# find /etc/icingaweb2
/etc/icingaweb2
/etc/icingaweb2/modules
/etc/icingaweb2/modules/translation
/etc/icingaweb2/modules/translation/config.ini
```

It's also from a package (`icingaweb2-common`):
```
root@50f77b52b865:/etc/icingaweb2# dpkg -S /etc/icingaweb2/modules/translation/config.ini
icingaweb2-common: /etc/icingaweb2/modules/translation/config.ini
root@50f77b52b865:/etc/icingaweb2# apt show icingaweb2
Package: icingaweb2
[...]
Depends: icingaweb2-common (= 2.4.0-1~debmon8+1), [...]
[...]
```

**Comment by jjethwa** [comment]
Hi @bebehei 

I'm unable to reproduce the issue.  The first test run on my local is against an instance with no volume

```
sudo docker run -p 80:80 --name icinga2 -t jordan/icinga2:2.6.0
```

```
root@c56024343f2d:/# find /etc/icingaweb2 | wc -l
1305
```

What tag are you using?

**Comment by bebehei** [comment]
> What tag are you using?

It had been using latest during pull-time. But I could also reproduce it with self-built image from two commits behind master.

But this may have been a mistake. I'll have to research and I'll close this issue or open a PR with the solution.

**Comment by jjethwa** [comment]
Thanks @bebehei 

Looking forward to your results.  BTW, I tried adding the interactive flag (-i) but could not reproduce the issue as well.

**Comment by bebehei** [comment]
Ok, it had been a false positive. I know why this had been a problem: I created a malfunctioning commit. On docker-build on my own machine, I mixed up the tags.
