### ISSUE TITLE
YUM is missing

### ISSUE THREAD

**Issue by stavrosg** [jjethwa/icinga2#70]
Hi, Thanks for the awesome container btw, an fyi.

Centos updated they're base image recently. They removed some packages.

https://github.com/CentOS/sig-cloud-instance-images/issues/40

**Comment by bebehei** [comment]
https://github.com/jjethwa/icinga2/blob/master/Dockerfile#L4

Only one single bug report!? I would shout out very loud SPAM!

**Comment by bebehei** [comment]
To clearify for all the others, who don't know in future, what `Dockerfile` had on line 4:
> FROM debian:jessie
