### ISSUE TITLE
container still running if icinga2 fails.

### ISSUE THREAD

**Issue by bebehei** [jjethwa/icinga2#72]
To get #67 merged, I'll record all non-showstoppers by adding new issues.

If the startup of icinga2 fails (configuration fail/whatever), the container will still run, although icinga2 does not do anything. This is a full antipattern against docker's understanding of containers.

To instantly fix this, I would have to get better knowledge of supervisord.

**Comment by jjethwa** [comment]
@bebehei 

The only downside to this is that there will be no way for a user to determine what caused Icinga2 to fail if the container is stopped automatically and the logs are not being stored in a volume.  Maybe if icinga2 startup fails, cat the last X lines from the icinga2 supervisor stdout log file to docker stdout?

**Comment by bebehei** [comment]
Yes. My favorite solution I wanted, was just piping the whole stdout/err via supervisord out. But I haven't found one.

**Comment by bebehei** [comment]
> The only downside to this is that there will be no way for a user to determine what caused Icinga2 to fail if the container is stopped automatically and the logs are not being stored in a volume. Maybe if icinga2 startup fails, cat the last X lines from the icinga2 supervisor stdout log file to docker stdout?

Fixed this by piping output from supervisor-scripts via supervisor to console, which is managed by docker (run|logs|...). See #74

**Comment by bebehei** [comment]
I believe after merging #74 this can be closed, too.
