### ISSUE TITLE
How to configure hosts etc.

### ISSUE THREAD

**Issue by deradam** [jjethwa/icinga2#8]
This is not really an issue but more a request for help. I started the container successfully and now I can access the web UI. However I wonder how I can add the configuration if I cannot ssh into the container. Any example would be appreciated.

**Comment by jjethwa** [comment]
Hi @deradam

The container has a few volumes (readme shows full list).   I would either use them with a data only container or have the configs available from the host VM.   See: https://docs.docker.com/userguide/dockervolumes/

You can also use nsenter to enter the container name space: https://github.com/jpetazzo/nsenter

**Comment by jjethwa** [comment]
Hi @deradam 

I'll go ahead and close this issue for now but please feel free to ask me any questions related to volumes and I'll answer as best as I can :)
