### ISSUE TITLE
Refusing to render the configuration, your DB layer corrupts binary data. You might be affected by Zend Framework bug #655

### ISSUE THREAD

**Issue by donnib** [jjethwa/icinga2#86]
Hi,
I get this when i try to deploy in Icinga Director, any ideas what is causing this ?

```
#0 /etc/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(149): Icinga\Module\Director\IcingaConfig\IcingaConfig->generateFromDb()
#1 /etc/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(185): Icinga\Module\Director\IcingaConfig\IcingaConfig->hasBeenModified()
#2 /etc/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(138): Icinga\Module\Director\IcingaConfig\IcingaConfig->storeIfModified()
#3 /etc/icingaweb2/modules/director/application/controllers/ConfigController.php(57): Icinga\Module\Director\IcingaConfig\IcingaConfig::generate(Object(Icinga\Module\Director\Db))
#4 /usr/share/php/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\ConfigController->deployAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('deployAction')
#6 /usr/share/php/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

donnib

**Comment by bebehei** [comment]
Thank you for the bug report.

The related bug (zendframework/zf1#655) should have been fixed, see here: https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/80-FAQ.md#binary-data-corruption-with-zf-1126-and-11217

I'm Currently researching this, why the icingaweb2-package is still invalid.

Could you please verify, that you're using the latest docker image?

**Comment by bebehei** [comment]
Ok, I see the trouble:

In #67 we updated a bunch of stuff. One bit of the change was moving the modules from `/etc/icingaweb2/modules` to a folder inside the container and not in the volume.

Could you please remove the modules `director`, `doc`, `graphite`, `monitoring` in your `/etc/icingaweb2/modules` volume?

This should then be fixed, because then the latest icingaweb2 director will be used.

**Comment by donnib** [comment]
I solved my problem by using the latest docker image.
