### ISSUE TITLE
Access to /usr/lib/nagios/plugins

### ISSUE THREAD

**Issue by donnib** [jjethwa/icinga2#87]
Hi,
If i want to make an plugin can i get access to the /usr/lib/nagios/plugins folder somehow ? It's not in the path list that you have. Do i really have to fork and then add it as a volume or can you add it ?

donnib

**Comment by bebehei** [comment]
Do you want to install additional packages? Just use `/opt/custom_run` and add there the neccessary apt-calls

**Comment by donnib** [comment]
I want to make a custom check and as far as i understand i have to place them in the above folder, i want to make a bash script that does a check.

**Comment by bebehei** [comment]
Or do you have self-written check-plugins? These should go normally in a separate volume, and then the CheckCommand-Object should use the different path/constant.

somewhere in zones.d or in constants.conf:
```
const CustomPluginDir = "/volume/icinga2"
```

checkCommand:
```
object CheckCommand "printer" {
  import "plugin-check-command"
  command = [ CustomPluginDir  + "/check_snmp_printer"]
  [...]
}
```
Put your check into `./check-plugins` and execute docker with the volume `-v $PWD/check-plugins:/volume/icinga2`

**Comment by donnib** [comment]
Yes this is exactly what i was looking for, thank you, on a side note, shoudl the docker image have SSH enabled, after i installed it a started it up icinga2 complains with ssh to localhost. Maybe it's just something on my side.

**Comment by bebehei** [comment]
Other way around, that check should not be existent in the docker image. There is no ssh needed in your container, so we should not check that.

**Comment by donnib** [comment]
ok sure, thanks. I will just ignore it at the moment since i don't know how i can remove that check ;)

**Comment by bebehei** [comment]
Just to be sure, you're not using the container wrong: Have you `/etc/icinga2` mounted as a docker-volume? If not, copy this data out, before destroy your container.

If you've got specific questions for icinga2 (general questions about configuration, monitoring strategies, etc..), you can also ask on [icinga-users mailing list](https://lists.icinga.org/mailman/listinfo/icinga-users).  That's a very good source of knowledge.

**Comment by donnib** [comment]
I have mounted /etc/icinga2 to a local folder, i change things in that folder so i guess i am ok. sure thanks for the tip.

**Comment by bebehei** [comment]
And as you're using icinga2-director, you should make `/var/lib/mysql` also a volume, as icinga2-director saves its data there.

For a full reference consult the [volume reference in README.md](https://github.com/jjethwa/icinga2#volume-reference)

**Comment by donnib** [comment]
Yes i am so good point ;)
