### ISSUE TITLE
Icinga Logs to Stdout

### ISSUE THREAD

**Issue by mastermindg** [jjethwa/icinga2#95]
I imported an existing configuration on top of this container via a volume. There were some missing dependencies that were causing icinga2 to crash. I had to quickly tail the log to get the info before the container crashed. It would be better if this log were piped to stdout so that the logs would be clearly accessible via docker logs.

**Comment by bebehei** [comment]
Since 76ee8411e97b34d6d2767f1018b96889e0252d75 the logs are piped to stdout and are crawlable via `docker logs`.

**Comment by bebehei** [comment]
🤦‍ Sorry, I got this fully wrong.

Here the correct answer:

No, It's not possible to log to stdout. This would require a big structural change in the container.

Please mount a volume on `/var/log/icinga2` to extract the log.

**Comment by jjethwa** [comment]
I agree with @bebehei 

icinga2 logs should be read from the /var/log/icinga2 volume.  stdout of the container should be the supervisor output as it is currently 😃

**Comment by mastermindg** [comment]
I respectfully disagree with both of you. 1) It's not a huge structural change...it's a single line added to the Dockerfile and 2) all logs in the Docker world should be piped to stdout/stderr to facilitate management under scale. I've got some other stuff I'll need to add to it anyway so I'll create a fork. Good work on this. Thanks!

**Comment by jjethwa** [comment]
@mastermindg Since supervisor is needed to control the other daemons, we decided that the output from it is more important during startup and status checking.  I can the use case you mention though.  Perhaps a user configurable variable might be an option.

**Comment by mastermindg** [comment]
I think it's always worth having more logs than less...and switches are great too :)
