### ISSUE TITLE
NodeName Generation

### ISSUE THREAD

**Issue by mastermindg** [jjethwa/icinga2#98]
I'm attempting to setup Icinga2 clients on my network. The clients have defined communication to the master which has a set NodeName and TicketSalt. If this changes do all of the clients of that master have to be reconfigured for the new master hostname?

**Comment by bebehei** [comment]
Yes. In general, if the CN of the certificate changes and does not match the hostname of the peer, the SSL-Connection from client to master cannot be negotiated anymore.

This is valid for any communication between icinga2 master and client.

But icinga2 implements SSL a bit more complex, which is yet more flexible: The master creates its own CA and every client trusts this CA. If you update the master's name and change its common name, the clients don't trust the master anymore. But you only have to create a new cert for the master matching the current common-name signed by the existing CA. Then you only have to update the clients, by telling them in their icinga2-configuration (i guess `zones.conf`), where the new master is (DNS hostname or IP-address update). Rekeying and updating new client certs is not needed.

**Comment by bebehei** [comment]
The ticket salt is a nonce, which is generated on the master. This nonce gets is bound to the client's hostname and verifies a client's request to sign its certificate by the master CA. After the certificate is signed by the master CA, the TicketSalt given to the client ist not needed anymore and can be thrown away.

**Comment by bebehei** [comment]
If you have icinga2-specific questions, please consult the [icinga-users mailinglist](https://lists.icinga.org/mailman/listinfo/icinga-users). The icinga2 devs are there around, too.

For anything, which is docker-related, the GH-issuetracker is still the right thing 😉
